HTTP/1.1 403 
X-Request-Id: a8f117d6-f809-4ad7-bfbc-8935493962b3
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:54:54 GMT

{"instance":"urn:uuid:a8f117d6-f809-4ad7-bfbc-8935493962b3","status":403,"title":"Forbidden"}