HTTP/1.1 200 
X-Request-Id: fc9376ad-d8a9-4e88-a690-f6aa556cfb6f
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:54:54 GMT

{"items":[{"occurredAt":"2026-10-04T01:54:54.801Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"OKAMvZaX","requestId":"ca129edf-d5f5-425b-aa49-4e4865bb48b8","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}