HTTP/1.1 201 
X-Request-Id: 74a42b54-b26a-4f2c-be78-798fe61803e5
Location: /api/links/hiRI8L6f
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:54:57 GMT

{"code":"hiRI8L6f","shortUrl":"http://localhost:8080/hiRI8L6f","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:54:57.363Z"}