HTTP/1.1 200 
X-Request-Id: 81531af1-a3bc-4f13-b6b7-f835982fafe6
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:54:57 GMT

{"items":[{"occurredAt":"2026-10-04T01:54:57.395Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"hiRI8L6f","requestId":"74a42b54-b26a-4f2c-be78-798fe61803e5","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}