HTTP/1.1 201 
X-Request-Id: a543fa63-ba30-4d82-bf30-7d040fda6c2d
Location: /api/links/dvAo9cwz
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:55:04 GMT

{"code":"dvAo9cwz","shortUrl":"http://localhost:8080/dvAo9cwz","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:55:04.133Z"}