HTTP/1.1 201 
X-Request-Id: b36f2a53-cea1-4643-8048-a1037470e3f8
Location: /api/links/dDSZJX1H
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:55:06 GMT

{"code":"dDSZJX1H","shortUrl":"http://localhost:8080/dDSZJX1H","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:55:06.546Z"}