HTTP/1.1 201 
X-Request-Id: bd76a155-5c90-4d98-8fdc-675aff5d5623
Location: /api/links/oQPF6bNd
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:55:08 GMT

{"code":"oQPF6bNd","shortUrl":"http://localhost:8080/oQPF6bNd","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:55:08.700Z"}