HTTP/1.1 201 
X-Request-Id: ca0d57d6-13b8-43e1-805d-9075b63df5d3
Location: /api/links/zcqJlj5c
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:55:10 GMT

{"code":"zcqJlj5c","shortUrl":"http://localhost:8080/zcqJlj5c","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:55:10.783Z"}