HTTP/1.1 201 
X-Request-Id: 0d61e7f8-6614-4fee-a5ac-6f0f29f113fd
Location: /api/links/9AVZ3LTf
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:55:13 GMT

{"code":"9AVZ3LTf","shortUrl":"http://localhost:8080/9AVZ3LTf","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:55:12.976Z"}