HTTP/1.1 201 
X-Request-Id: 520c3066-6e22-4802-9d7e-0829ae7a7fea
Location: /api/links/Pe81cSLF
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:37 GMT

{"code":"Pe81cSLF","shortUrl":"http://localhost:8080/Pe81cSLF","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:44:00Z"}