HTTP/1.1 201 
X-Request-Id: fc923b9a-c922-43e4-ba70-9c924824b0a6
Location: /api/links/3558SKNY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:40 GMT

{"code":"3558SKNY","shortUrl":"http://localhost:8080/3558SKNY","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:36:00Z"}