HTTP/1.1 429 
X-Request-Id: 9ab58f4b-5ea7-4e58-95be-9cbf4a11d2bd
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:36 GMT

{"instance":"urn:uuid:9ab58f4b-5ea7-4e58-95be-9cbf4a11d2bd","status":429,"title":"Too Many Requests"}