HTTP/1.1 201 
X-Request-Id: 852d54bc-89e8-419d-8644-9f9f95b0ab19
Location: /api/links/S6jVU2vo
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:36 GMT

{"code":"S6jVU2vo","shortUrl":"http://localhost:8080/S6jVU2vo","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:20:00Z"}