HTTP/1.1 302 
X-Request-Id: c3e5a88a-f337-4517-808d-14046fcbbb59
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:39 GMT

