HTTP/1.1 302 
X-Request-Id: 6e6219f4-34ad-4040-a4a9-440d4bafb07f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:36 GMT

