HTTP/1.1 429 
X-Request-Id: 34c3dbda-aaa0-4ba5-95e6-87a6394c3e9c
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:37 GMT

{"instance":"urn:uuid:34c3dbda-aaa0-4ba5-95e6-87a6394c3e9c","status":429,"title":"Too Many Requests"}