HTTP/1.1 429 
X-Request-Id: 28d1c48b-470b-4deb-8e4a-052908e47f30
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:35 GMT

{"instance":"urn:uuid:28d1c48b-470b-4deb-8e4a-052908e47f30","status":429,"title":"Too Many Requests"}