HTTP/1.1 302 
X-Request-Id: c989d2b1-87df-4cd2-bdef-30887ce53d6f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:37 GMT

