HTTP/1.1 429 
X-Request-Id: 576c67ef-6cd6-40c9-a264-3b98a36a3f1b
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:38 GMT

{"instance":"urn:uuid:576c67ef-6cd6-40c9-a264-3b98a36a3f1b","status":429,"title":"Too Many Requests"}