HTTP/1.1 302 
X-Request-Id: 1cb8efec-7965-49e7-ad41-0b43b3966e1c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:35 GMT

