HTTP/1.1 302 
X-Request-Id: df41fe2c-80dd-425d-a0bc-d1adb6989aae
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:37 GMT

