HTTP/1.1 429 
X-Request-Id: d23247f9-508c-4f95-bada-72d9813e505e
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:38 GMT

{"instance":"urn:uuid:d23247f9-508c-4f95-bada-72d9813e505e","status":429,"title":"Too Many Requests"}