HTTP/1.1 201 
X-Request-Id: 41c8bddd-794a-4157-a655-08c76f5ce85b
Location: /api/links/5qZFn4Ky
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:39 GMT

{"code":"5qZFn4Ky","shortUrl":"http://localhost:8080/5qZFn4Ky","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}