HTTP/1.1 302 
X-Request-Id: 4158eae8-527d-4a7a-8998-f9939ac97c11
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

