HTTP/1.1 201 
X-Request-Id: cf3e30f2-2947-481e-8e09-4b14f8032a6f
Location: /api/links/xXisOedI
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:35 GMT

{"code":"xXisOedI","shortUrl":"http://localhost:8080/xXisOedI","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:12:00Z"}