HTTP/1.1 302 
X-Request-Id: d933da68-b559-4ecd-8126-70c12ace3f4f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:35 GMT

