HTTP/1.1 429 
X-Request-Id: cc123eea-0fb9-452f-b1ba-9071a79092a1
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:40 GMT

{"instance":"urn:uuid:cc123eea-0fb9-452f-b1ba-9071a79092a1","status":429,"title":"Too Many Requests"}