HTTP/1.1 429 
X-Request-Id: 59961dd7-5756-41d3-bddb-7d643a65b155
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:36 GMT

{"instance":"urn:uuid:59961dd7-5756-41d3-bddb-7d643a65b155","status":429,"title":"Too Many Requests"}