HTTP/1.1 201 
X-Request-Id: c795011e-7cf0-498f-bed3-a7da58e8d252
Location: /api/links/6nijSJAi
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:38 GMT

{"code":"6nijSJAi","shortUrl":"http://localhost:8080/6nijSJAi","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:56:00Z"}