HTTP/1.1 302 
X-Request-Id: ef869afe-fbbb-4f92-9d53-95cf3e7cf88a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

