HTTP/1.1 429 
X-Request-Id: a4dd1537-f7af-4007-b496-23b6fd926b00
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:39 GMT

{"instance":"urn:uuid:a4dd1537-f7af-4007-b496-23b6fd926b00","status":429,"title":"Too Many Requests"}