HTTP/1.1 302 
X-Request-Id: 4d17fe0a-de2e-415f-9883-2e6177b0fd37
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:39 GMT

