HTTP/1.1 429 
X-Request-Id: cb1e2ef3-3bbd-428c-9372-39978a4b2d9d
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:39 GMT

{"instance":"urn:uuid:cb1e2ef3-3bbd-428c-9372-39978a4b2d9d","status":429,"title":"Too Many Requests"}