HTTP/1.1 302 
X-Request-Id: a60b7457-e180-4427-bd56-2a3e0ed56ea7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:36 GMT

