HTTP/1.1 302 
X-Request-Id: 361de249-9797-4ac7-ad49-d93185c9f619
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

