HTTP/1.1 302 
X-Request-Id: 4ee4d733-0fa2-4048-8685-60d564793c25
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:37 GMT

