HTTP/1.1 201 
X-Request-Id: 22de8e46-f126-48db-aa86-b340dacbe8c9
Location: /api/links/0O50USEt
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:39 GMT

{"code":"0O50USEt","shortUrl":"http://localhost:8080/0O50USEt","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:28:00Z"}