HTTP/1.1 201 
X-Request-Id: 27c798fb-7980-451e-ab85-8d37b9244581
Location: /api/links/GlnwtxyX
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:38 GMT

{"code":"GlnwtxyX","shortUrl":"http://localhost:8080/GlnwtxyX","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}