HTTP/1.1 201 
X-Request-Id: 817a4898-e5e1-41b4-a3ac-c9be3a225b4c
Location: /api/links/CEK8fQBe
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:38 GMT

{"code":"CEK8fQBe","shortUrl":"http://localhost:8080/CEK8fQBe","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:08:00Z"}