HTTP/1.1 302 
X-Request-Id: cb7e9d38-54a1-413b-84b8-4a11f8fadb57
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

