HTTP/1.1 201 
X-Request-Id: 68a7797b-199f-4258-b077-16d054694a65
Location: /api/links/04d8qttO
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:39 GMT

{"code":"04d8qttO","shortUrl":"http://localhost:8080/04d8qttO","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:24:00Z"}