HTTP/1.1 302 
X-Request-Id: 0f5fdf59-61a8-40a7-917f-692f7bac0eb4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:37 GMT

