HTTP/1.1 429 
X-Request-Id: c50e47fb-9c07-433c-a0d3-0f6297adb639
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 03:07:37 GMT

{"instance":"urn:uuid:c50e47fb-9c07-433c-a0d3-0f6297adb639","status":429,"title":"Too Many Requests"}