HTTP/1.1 302 
X-Request-Id: 2a79e1b8-5798-4a38-a4a3-e65fcb6c6942
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:39 GMT

