HTTP/1.1 201 
X-Request-Id: 6c27c7eb-7265-414c-9954-8bdc4e0fe675
Location: /api/links/jSd9D1TR
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:35 GMT

{"code":"jSd9D1TR","shortUrl":"http://localhost:8080/jSd9D1TR","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:16:00Z"}