HTTP/1.1 302 
X-Request-Id: e570bff1-de48-4efc-8450-c4fd32150799
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

