HTTP/1.1 302 
X-Request-Id: b30f0d59-5863-45e0-a9fa-e11f327a4ff1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

