HTTP/1.1 302 
X-Request-Id: 576bffd1-58ae-4512-8385-06a10c198223
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:36 GMT

