HTTP/1.1 302 
X-Request-Id: 779c1cc4-df1e-4f9e-8ce3-739133e89fb6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:38 GMT

