HTTP/1.1 201 
X-Request-Id: 453cf989-e391-41ad-bc2f-41b550f9bce3
Location: /api/links/1yazXbYT
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 03:07:38 GMT

{"code":"1yazXbYT","shortUrl":"http://localhost:8080/1yazXbYT","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:56:00Z"}