HTTP/1.1 302 
X-Request-Id: 553da87d-800e-47b6-a9da-3db43e24e62e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:36 GMT

