HTTP/1.1 302 
X-Request-Id: 970f9060-ba64-4fe5-8ac0-5d8cf58ca5fb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 03:07:39 GMT

