HTTP/1.1 302 
X-Request-Id: 4968dc29-3512-4708-8e04-62e671e3716f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

