HTTP/1.1 302 
X-Request-Id: 26cd114e-6986-4972-a765-9769804c1e9b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

