HTTP/1.1 201 
X-Request-Id: 523eaa42-4250-440c-b443-9cd8ba14e45e
Location: /api/links/5ejccjJ3
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"5ejccjJ3","shortUrl":"http://localhost:8080/5ejccjJ3","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:20:00Z"}