HTTP/1.1 302 
X-Request-Id: 16783612-856e-46b9-b6df-7fb0f8e21834
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:05 GMT

