HTTP/1.1 302 
X-Request-Id: 68917d11-9424-45d0-b643-83656eb628dc
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

