HTTP/1.1 302 
X-Request-Id: 77e78180-3dda-4524-9d43-340b4f38068a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

