HTTP/1.1 302 
X-Request-Id: 02087d36-9a10-4a6f-ae6b-26e441330d81
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

