HTTP/1.1 302 
X-Request-Id: 024f6b3d-554e-48b9-9b44-ff47a7e793ad
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

