HTTP/1.1 302 
X-Request-Id: 777c28f9-d8e2-497e-8650-a6a61c8ae695
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

