HTTP/1.1 429 
X-Request-Id: 76ebe58f-777a-4057-884e-c73d08ec319c
Retry-After: 1
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:10:48 GMT

{"instance":"urn:uuid:76ebe58f-777a-4057-884e-c73d08ec319c","status":429,"title":"Too Many Requests"}