HTTP/1.1 302 
X-Request-Id: faaab574-0ca6-47be-b7e3-ac24f97f4b32
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:16 GMT

