HTTP/1.1 429 
X-Request-Id: dd17f14e-dcee-4a98-8360-cf62fd0f6f5f
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"instance":"urn:uuid:dd17f14e-dcee-4a98-8360-cf62fd0f6f5f","status":429,"title":"Too Many Requests"}