HTTP/1.1 302 
X-Request-Id: 8012e140-2c9b-491a-a4be-0c51d500754d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

