HTTP/1.1 302 
X-Request-Id: 7b397300-6a6e-4e18-9266-a68d595721d9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

