HTTP/1.1 302 
X-Request-Id: fbc3ae92-4b3e-4244-bc60-dce996ef056a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

