HTTP/1.1 302 
X-Request-Id: ce1708b8-092f-471d-8565-0ca3a009fc5c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

