HTTP/1.1 302 
X-Request-Id: 1be7d4df-e147-4599-8dce-471190841106
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:31 GMT

