HTTP/1.1 302 
X-Request-Id: b9487481-c4ee-486c-8cc9-b38a7a57899c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

