HTTP/1.1 302 
X-Request-Id: d088f6b7-9fce-4aee-9567-7dd94ffd1af8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

