HTTP/1.1 403 
X-Request-Id: a046c012-d584-46bb-966d-18d5060b201c
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:22 GMT

{"instance":"urn:uuid:a046c012-d584-46bb-966d-18d5060b201c","status":403,"title":"Forbidden"}