HTTP/1.1 201 
X-Request-Id: 04890860-0e18-4375-b814-9ab7de94d8c8
Location: /api/links/pD4OX5X0
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:15 GMT

{"code":"pD4OX5X0","shortUrl":"http://localhost:8080/pD4OX5X0","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:24:00Z"}