HTTP/1.1 200 
X-Request-Id: b7bc28bd-c4fe-4195-9db9-1483189f06a8
Content-Type: application/json
Content-Length: 184
Date: Sun, 04 Oct 2026 02:11:32 GMT

{"code":"msJjSJIY","totalClicks":21,"clicksPerDay":[{"date":"2026-10-01","clicks":21,"uniqueVisitors":2,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":21}]}