HTTP/1.1 302 
X-Request-Id: 98ba68a0-785c-4f5a-8d06-dd78507e01c0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

