HTTP/1.1 302 
X-Request-Id: c61dfe4c-ffc8-4022-b0e0-3827953ae56c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

