HTTP/1.1 302 
X-Request-Id: 1f65241c-9215-4f48-bf1e-e9fb34101832
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

