HTTP/1.1 302 
X-Request-Id: 43274fa5-b3a3-462d-8f6a-be4d11ddeaee
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

