HTTP/1.1 302 
X-Request-Id: 27e3c4ef-377d-4c10-8f27-8b0051fbe985
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

