HTTP/1.1 302 
X-Request-Id: fc000adc-bf9d-44e1-9b45-10e35dd4b01f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

