HTTP/1.1 302 
X-Request-Id: b1424924-3ac4-4fd9-bf84-264b45c387ac
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

