HTTP/1.1 302 
X-Request-Id: f5c139d3-8cfa-4413-948f-dfdb09e4360a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

