HTTP/1.1 302 
X-Request-Id: 01eda79c-b21d-4012-b69e-b156b9962df5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

