HTTP/1.1 302 
X-Request-Id: dc42aa82-3b35-4033-991b-3f0106695f5a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

