HTTP/1.1 302 
X-Request-Id: d51f9c29-a8c8-40ea-be68-27a54fc9341d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

