HTTP/1.1 302 
X-Request-Id: 2decf190-e477-4020-9528-4d33fb3ba2d2
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

