HTTP/1.1 302 
X-Request-Id: c323c69f-c648-4b6b-af9e-ba87a727bd29
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

