HTTP/1.1 302 
X-Request-Id: 71e8586e-0a08-4386-a839-9306f4257bb8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

