HTTP/1.1 302 
X-Request-Id: 08552823-5b28-4fef-a2c4-af743e7f6ed6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

