HTTP/1.1 302 
X-Request-Id: b6178e3d-6ddc-4934-9897-0791f355b5b7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

