HTTP/1.1 429 
X-Request-Id: d76db36e-1c47-4717-9788-804e3946c9bb
Retry-After: 1
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:10:51 GMT

{"instance":"urn:uuid:d76db36e-1c47-4717-9788-804e3946c9bb","status":429,"title":"Too Many Requests"}