HTTP/1.1 302 
X-Request-Id: cce29ef3-6a47-4f50-8d80-9fd447c0a95f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

