HTTP/1.1 302 
X-Request-Id: c430a77f-2723-49dc-91b8-fc6069fdebe8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

