HTTP/1.1 302 
X-Request-Id: bc68cf90-2191-4430-b14a-c330cf3739ba
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

