HTTP/1.1 302 
X-Request-Id: 67ea7bcb-ebe0-4682-b7c3-1d9b1411843c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

