HTTP/1.1 302 
X-Request-Id: bb6015ac-4276-45aa-8303-e848f13873c4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

