HTTP/1.1 302 
X-Request-Id: 4bde0736-b28c-4c33-b030-34c0cf4264cc
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

