HTTP/1.1 429 
X-Request-Id: f5539d7b-9aee-44cb-8126-abf5036102aa
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:16 GMT

{"instance":"urn:uuid:f5539d7b-9aee-44cb-8126-abf5036102aa","status":429,"title":"Too Many Requests"}