HTTP/1.1 302 
X-Request-Id: 36e944e7-03dd-4328-856b-b95a95bf3d9b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

