HTTP/1.1 201 
X-Request-Id: cf933c43-f4d3-4106-ab08-2ad1a062a5c0
Location: /api/links/yAGfMUE7
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:10:51 GMT

{"code":"yAGfMUE7","shortUrl":"http://localhost:8080/yAGfMUE7","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:00:00Z"}