HTTP/1.1 302 
X-Request-Id: 49c27cd8-9ae1-4ddc-a7e5-4a3955750ceb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

