HTTP/1.1 302 
X-Request-Id: d71e51d5-6844-4aaa-b2fb-834a509fe457
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

