HTTP/1.1 302 
X-Request-Id: ea66644b-c1aa-441e-936a-f190d1c3e4b7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

