HTTP/1.1 302 
X-Request-Id: d7d7b0b1-a5de-43c1-bec5-26e72346ee56
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

