HTTP/1.1 302 
X-Request-Id: f6bb48d8-4164-4b97-86dd-b4ffce65f0fd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

