HTTP/1.1 302 
X-Request-Id: ef7c3b7f-c52c-43c4-8024-e5746eeb388f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

