HTTP/1.1 302 
X-Request-Id: b91d712c-bde0-497d-a828-1cb2332dd8ba
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

