HTTP/1.1 201 
X-Request-Id: 56f66832-955e-4a76-84ad-531732b18362
Location: /api/links/tZKrxcN1
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:16 GMT

{"code":"tZKrxcN1","shortUrl":"http://localhost:8080/tZKrxcN1","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:48:00Z"}