HTTP/1.1 302 
X-Request-Id: e9a67e0f-7c77-499f-8f6a-305fc735d8ae
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

