HTTP/1.1 302 
X-Request-Id: 6b50e702-7d13-46a0-8049-fe2b72a400d0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

