HTTP/1.1 302 
X-Request-Id: 60694713-1215-48f3-9b72-0a7ac9cac355
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:09 GMT

