HTTP/1.1 302 
X-Request-Id: afd26a6f-5763-49cf-99c2-17053085da54
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

