HTTP/1.1 302 
X-Request-Id: 886bd90c-7ba3-4f67-8d17-f678424528be
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

