HTTP/1.1 201 
X-Request-Id: 7888c2bb-199b-4977-a9b5-51a534e105b6
Location: /api/links/gyxU8Owo
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:15 GMT

{"code":"gyxU8Owo","shortUrl":"http://localhost:8080/gyxU8Owo","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:24:00Z"}