HTTP/1.1 201 
X-Request-Id: 8878ba1e-f366-4627-b2bd-5d54ed2dd2e0
Location: /api/links/XTyw7lm3
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:19 GMT

{"code":"XTyw7lm3","shortUrl":"http://localhost:8080/XTyw7lm3","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:36:00Z"}