HTTP/1.1 302 
X-Request-Id: 07e39dcd-c3cf-49fe-8286-36b5a37688d7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

