HTTP/1.1 302 
X-Request-Id: 9e64eaf2-a51d-4179-bd31-686c1dae11b1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

