HTTP/1.1 302 
X-Request-Id: 8de27f84-b1ee-411f-a91c-5f82178c936a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:32 GMT

