HTTP/1.1 302 
X-Request-Id: 9092e05e-1e48-40a8-8471-d2d4c83f740d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

