HTTP/1.1 302 
X-Request-Id: 31d413b4-b46b-47e0-b19d-2e61dd0b9260
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:05 GMT

