HTTP/1.1 200 
X-Request-Id: bae434b5-591e-42dc-94eb-998472385245
Content-Type: application/json
Content-Length: 181
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"Sjk73sN7","totalClicks":3,"clicksPerDay":[{"date":"2026-10-01","clicks":3,"uniqueVisitors":2,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":3}]}