HTTP/1.1 302 
X-Request-Id: fd1920b6-427d-4c11-ae66-7acdd7a4b114
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

