HTTP/1.1 201 
X-Request-Id: 74391609-b0a7-44f5-b6db-7f047c8b6d16
Location: /api/links/pPqeycQH
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"pPqeycQH","shortUrl":"http://localhost:8080/pPqeycQH","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:28:00Z"}