HTTP/1.1 302 
X-Request-Id: fb0b961c-f375-4188-8ec9-1a18f1555652
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

