HTTP/1.1 429 
X-Request-Id: 0d6bd951-deb1-4150-b69e-a524f1c2fd4e
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"instance":"urn:uuid:0d6bd951-deb1-4150-b69e-a524f1c2fd4e","status":429,"title":"Too Many Requests"}