HTTP/1.1 302 
X-Request-Id: 8467ed75-adc4-4d19-ab09-6d503797ad82
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

