HTTP/1.1 429 
X-Request-Id: c9e18899-6754-4f1d-b845-8f5c51e1724e
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:16 GMT

{"instance":"urn:uuid:c9e18899-6754-4f1d-b845-8f5c51e1724e","status":429,"title":"Too Many Requests"}