HTTP/1.1 302 
X-Request-Id: 2ed61dd6-560b-459a-bc21-9374d6e311d6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

