HTTP/1.1 302 
X-Request-Id: a09749a5-860e-426c-9c19-b2ee6e76b885
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

