HTTP/1.1 302 
X-Request-Id: 18670a4e-9c74-4c9d-b4c9-c57ea83f788e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

