HTTP/1.1 302 
X-Request-Id: 4ad1594c-d9d1-4bbd-8de7-346ce1dcf053
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

