HTTP/1.1 302 
X-Request-Id: 6d6b5061-67a1-4ae3-b515-e21340e6a2d7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

