HTTP/1.1 302 
X-Request-Id: 04d6274a-4d91-4e33-a36f-26a81dc593df
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

