HTTP/1.1 302 
X-Request-Id: d0d8d61b-d2a3-417c-b411-9de5085a90e0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

