HTTP/1.1 302 
X-Request-Id: a33d4fe9-2253-4138-98dc-0b58c194907f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

