HTTP/1.1 302 
X-Request-Id: 7ab58bc0-852d-4b09-ba5f-a06c7913f465
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

