HTTP/1.1 302 
X-Request-Id: 302fa05a-56aa-4b63-8b4a-de7c462e5d38
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:32 GMT

