HTTP/1.1 302 
X-Request-Id: 3f9dc668-f5f5-4b14-a272-4c3774f6451b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

