HTTP/1.1 302 
X-Request-Id: 61edb67c-d545-4b15-9a53-74440f7fb953
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

