HTTP/1.1 302 
X-Request-Id: 6ba74889-a028-48d0-9770-716e2b1acd68
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

