HTTP/1.1 201 
X-Request-Id: daf87dc9-cafe-4eeb-873e-94ae79c6996b
Location: /api/links/mMmbH3Vf
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"mMmbH3Vf","shortUrl":"http://localhost:8080/mMmbH3Vf","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}