HTTP/1.1 302 
X-Request-Id: 6475b82e-b558-4438-8f1b-5db732d395c7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

