HTTP/1.1 201 
X-Request-Id: dceb4f60-b2ce-4db1-86b9-6b32bb50d721
Location: /api/links/ojX2p2Pm
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:17 GMT

{"code":"ojX2p2Pm","shortUrl":"http://localhost:8080/ojX2p2Pm","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:04:00Z"}