HTTP/1.1 302 
X-Request-Id: 25ef76cd-2581-4f61-96a9-ada5b0722b80
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

