HTTP/1.1 201 
X-Request-Id: d8860caf-0ec7-4daf-a87a-c8eac455960f
Location: /api/links/R4pzWZxa
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:14 GMT

{"code":"R4pzWZxa","shortUrl":"http://localhost:8080/R4pzWZxa","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:12:00Z"}