HTTP/1.1 429 
X-Request-Id: 7dc73b3d-7a53-4f89-a7f1-3bb75e8aa6b3
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:19 GMT

{"instance":"urn:uuid:7dc73b3d-7a53-4f89-a7f1-3bb75e8aa6b3","status":429,"title":"Too Many Requests"}