HTTP/1.1 302 
X-Request-Id: fda6f7e1-6d63-4bf3-9216-8f6b14eaa7d4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

