HTTP/1.1 302 
X-Request-Id: bb7b6a1c-cfc7-4883-9d44-81bdc1d97620
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:18 GMT

