HTTP/1.1 302 
X-Request-Id: 18c38023-2c17-42d8-951a-57ce77d1f0e3
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

