HTTP/1.1 302 
X-Request-Id: 5129a020-3453-4c27-9720-e79e3a99f025
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:29 GMT

