HTTP/1.1 200 
X-Request-Id: c19465cb-0056-49cf-aefe-4892865ff214
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 156
Date: Sun, 04 Oct 2026 02:11:32 GMT

{"availableTags":[],"description":"Clicks written to the click store","measurements":[{"statistic":"COUNT","value":21.0}],"name":"urlshort.clicks.recorded"}