HTTP/1.1 302 
X-Request-Id: c60f6df9-e75b-4efa-9063-798dd18af039
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

