HTTP/1.1 302 
X-Request-Id: e9458c5f-f1b4-4587-a3c4-8e750bd8bfb1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

