HTTP/1.1 302 
X-Request-Id: e435b792-7d98-4e21-a6cd-9cfa6b8ea7cd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

