HTTP/1.1 429 
X-Request-Id: c75dba1b-8d89-462c-8ec0-79e5c03fef94
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:14 GMT

{"instance":"urn:uuid:c75dba1b-8d89-462c-8ec0-79e5c03fef94","status":429,"title":"Too Many Requests"}