HTTP/1.1 302 
X-Request-Id: 240d2ef7-5ef9-40a3-9066-f30813e6f4ea
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

