HTTP/1.1 302 
X-Request-Id: b44feaf4-3079-4035-9a3b-e23f2d77296e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

