HTTP/1.1 403 
X-Request-Id: ad1eec66-6a39-4ddf-a199-2c11aca2cdd2
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:25 GMT

{"instance":"urn:uuid:ad1eec66-6a39-4ddf-a199-2c11aca2cdd2","status":403,"title":"Forbidden"}