HTTP/1.1 302 
X-Request-Id: aa4da607-553c-4fb3-9171-1e42f60838c0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:18 GMT

