HTTP/1.1 302 
X-Request-Id: f49bb7be-1e05-4b79-ac04-5ae6d4258af3
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

