HTTP/1.1 403 
X-Request-Id: 56258a71-5dbb-4f5b-b06f-93fbb0ead33c
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:22 GMT

{"instance":"urn:uuid:56258a71-5dbb-4f5b-b06f-93fbb0ead33c","status":403,"title":"Forbidden"}