HTTP/1.1 302 
X-Request-Id: 740ec729-cec7-4c68-a2d7-4bcde20f2aec
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

