HTTP/1.1 302 
X-Request-Id: 62bdfaff-7420-4023-b897-ff3f4d54ad1e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

