HTTP/1.1 302 
X-Request-Id: f40b5f1d-bfa4-4314-a69c-0f0865a6b942
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

