HTTP/1.1 403 
X-Request-Id: 1221fee2-e320-4bbc-b9b1-1f4cec6cc538
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:10:46 GMT

{"instance":"urn:uuid:1221fee2-e320-4bbc-b9b1-1f4cec6cc538","status":403,"title":"Forbidden"}