HTTP/1.1 201 
X-Request-Id: aa90b153-230d-4325-a2ba-452add8860c4
Location: /api/links/w3O8ds3S
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"w3O8ds3S","shortUrl":"http://localhost:8080/w3O8ds3S","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:28:00Z"}