HTTP/1.1 302 
X-Request-Id: 38c3f0dd-e2a0-4dd9-aaee-64bc44658a8f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:16 GMT

