HTTP/1.1 302 
X-Request-Id: 78e9f21c-e66b-4cee-8627-5ab917fa7ffe
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:15 GMT

