HTTP/1.1 302 
X-Request-Id: 24e63983-3f18-4f38-a8e5-a33f34afd4ba
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

