HTTP/1.1 302 
X-Request-Id: df3586ab-2723-4b2b-a198-b10e15a7e21b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:19 GMT

