HTTP/1.1 302 
X-Request-Id: 42d85665-cad4-4768-a6f1-80df8b184a2a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

