HTTP/1.1 429 
X-Request-Id: e28f00f9-f488-4a0c-9254-2dc686dca3fc
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:17 GMT

{"instance":"urn:uuid:e28f00f9-f488-4a0c-9254-2dc686dca3fc","status":429,"title":"Too Many Requests"}