HTTP/1.1 302 
X-Request-Id: 90f0bec7-0eb3-432f-9e68-0c6dbca153b8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:45 GMT

