HTTP/1.1 302 
X-Request-Id: c9951cf5-4331-4de0-a2a0-bb4d364d7aa1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

