HTTP/1.1 302 
X-Request-Id: 9606a5d1-0c61-450c-b1ce-51b404c92eeb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

