HTTP/1.1 302 
X-Request-Id: 50e0f268-f5ae-49d1-8a1b-a8af9818e318
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

