HTTP/1.1 302 
X-Request-Id: 0bd2b13c-2e81-49b1-a62c-306421f249e1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

