HTTP/1.1 302 
X-Request-Id: 42e107d2-3e2c-4f29-9969-c8d5b5934491
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

