HTTP/1.1 302 
X-Request-Id: c45a989b-dd4e-4817-8ab6-f3200f9d0e03
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

