HTTP/1.1 302 
X-Request-Id: fbd44cdb-1ecc-4cc4-9978-5d999658b572
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

