HTTP/1.1 302 
X-Request-Id: 7dc358dc-8c21-4aae-8878-6c0da2ddfa7f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

