HTTP/1.1 200 
X-Request-Id: a6a0c688-aefd-44b3-9441-faade84f333a
Content-Type: application/json
Content-Length: 181
Date: Sun, 04 Oct 2026 02:11:15 GMT

{"code":"5gOxImw7","totalClicks":3,"clicksPerDay":[{"date":"2026-10-01","clicks":3,"uniqueVisitors":2,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":3}]}