HTTP/1.1 302 
X-Request-Id: 354cbc00-aa1a-42f3-b0cb-27f11428c5fa
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:18 GMT

