HTTP/1.1 302 
X-Request-Id: 2245aa16-0b3c-40ae-9402-6e8dd0cd980f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

