HTTP/1.1 302 
X-Request-Id: 433bb79f-8bb2-4e9f-b0b6-5aab8e3d2db8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

