HTTP/1.1 302 
X-Request-Id: 9399897c-5e16-4781-b7a2-556bf26a8b12
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:17 GMT

