HTTP/1.1 302 
X-Request-Id: 4a62428c-9312-4538-9a3b-0e066e5719df
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

