HTTP/1.1 302 
X-Request-Id: 44bdc685-8dd6-4fbe-9671-57a90d1c748d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

