HTTP/1.1 302 
X-Request-Id: a0c1d426-d33a-40e2-9a53-8c7ce46bd993
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:17 GMT

