HTTP/1.1 201 
X-Request-Id: b91fbcc0-25b9-49a6-8754-bc5cbc259f29
Location: /api/links/AzG4YmxH
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:16 GMT

{"code":"AzG4YmxH","shortUrl":"http://localhost:8080/AzG4YmxH","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:40:00Z"}