HTTP/1.1 403 
X-Request-Id: 16eb5798-0d8d-40ad-8b30-3130f7571d0f
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:22 GMT

{"instance":"urn:uuid:16eb5798-0d8d-40ad-8b30-3130f7571d0f","status":403,"title":"Forbidden"}