HTTP/1.1 302 
X-Request-Id: feedb239-8b99-4961-afd2-5706992ffc03
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

