HTTP/1.1 302 
X-Request-Id: 37a4cfb0-bb5d-4d9c-adcb-40af70282b5e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

