HTTP/1.1 302 
X-Request-Id: 707360a5-3f43-462c-b968-58047d14ea19
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

