HTTP/1.1 302 
X-Request-Id: bea50da1-c6aa-4653-8264-fba7c1c46dad
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

