HTTP/1.1 302 
X-Request-Id: ab5d519f-9a2d-4a11-9e92-8ceb413edde0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

