HTTP/1.1 302 
X-Request-Id: a10e575e-fd6e-4f0f-b975-2da0d6d224b0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:05 GMT

