HTTP/1.1 429 
X-Request-Id: e7610ef3-dcc0-49c3-9fc9-abe53f9b2178
Retry-After: 1
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:09 GMT

{"instance":"urn:uuid:e7610ef3-dcc0-49c3-9fc9-abe53f9b2178","status":429,"title":"Too Many Requests"}