HTTP/1.1 302 
X-Request-Id: 33ed706c-ad9c-4741-8050-03ebe0be9595
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

