HTTP/1.1 302 
X-Request-Id: ff757e48-3caf-4b3b-86fd-9e4ebc4220ec
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

