HTTP/1.1 302 
X-Request-Id: a0433901-f642-49e8-b560-531272619cae
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

