HTTP/1.1 302 
X-Request-Id: a2278375-b574-4fd9-b043-8c98b49f7546
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

