HTTP/1.1 201 
X-Request-Id: ace96b31-4d64-4329-8345-aa20e9a90780
Location: /api/links/7PeeVtHR
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:10:46 GMT

{"code":"7PeeVtHR","shortUrl":"http://localhost:8080/7PeeVtHR","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-02T12:06:00Z"}