HTTP/1.1 302 
X-Request-Id: ab20e1fa-be66-4213-9097-4cec4f02a169
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

