HTTP/1.1 200 
X-Request-Id: 13ad2967-2c7d-487d-b9e4-0f5a105f6bfc
Content-Type: application/json
Content-Length: 184
Date: Sun, 04 Oct 2026 02:11:29 GMT

{"code":"nFbPdF5q","totalClicks":21,"clicksPerDay":[{"date":"2026-10-01","clicks":21,"uniqueVisitors":1,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":21}]}