HTTP/1.1 429 
X-Request-Id: a2f69cb5-afba-4b72-950f-f6ee48e87f37
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:17 GMT

{"instance":"urn:uuid:a2f69cb5-afba-4b72-950f-f6ee48e87f37","status":429,"title":"Too Many Requests"}