HTTP/1.1 302 
X-Request-Id: 9a9496fe-bd6f-425c-980c-c29b4892316e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:05 GMT

