HTTP/1.1 302 
X-Request-Id: 6cf56f53-3761-4093-9ede-018cd4a56f41
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

