HTTP/1.1 201 
X-Request-Id: dd08e7a5-baa5-40a9-8ece-64fe12d895b4
Location: /api/links/WwxoWf4P
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:14 GMT

{"code":"WwxoWf4P","shortUrl":"http://localhost:8080/WwxoWf4P","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:16:00Z"}