HTTP/1.1 302 
X-Request-Id: fdfa380e-d4ca-4e0d-8d30-37877e2c6a4b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:29 GMT

