HTTP/1.1 302 
X-Request-Id: a64755a8-6a43-4157-89d9-b4ca837ded5c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

