HTTP/1.1 302 
X-Request-Id: a372e6d9-8c77-46c2-b092-7fcd595a6cbf
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

