HTTP/1.1 302 
X-Request-Id: 9c76679d-b97d-407d-993c-0b229aa678ec
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

