HTTP/1.1 302 
X-Request-Id: c6640192-2529-43c1-a94c-2c1025c9a535
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:01 GMT

