HTTP/1.1 429 
X-Request-Id: 0e5f3176-ba81-47be-8645-c7a1c7a81aba
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:16 GMT

{"instance":"urn:uuid:0e5f3176-ba81-47be-8645-c7a1c7a81aba","status":429,"title":"Too Many Requests"}