HTTP/1.1 302 
X-Request-Id: 9c5d8886-1a63-489d-8591-ef2692a81cfd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

