HTTP/1.1 201 
X-Request-Id: 3a5068b2-927c-4c06-8765-3ddec38de1ba
Location: /api/links/HvxY83G5
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:10:46 GMT

{"code":"HvxY83G5","shortUrl":"http://localhost:8080/HvxY83G5","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:04:00Z"}