HTTP/1.1 302 
X-Request-Id: ac5888bf-d5ea-4078-bfea-a5486c69791a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

