HTTP/1.1 302 
X-Request-Id: 72970e5c-4483-4405-9b77-d59f3e2ddedf
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

