HTTP/1.1 302 
X-Request-Id: a794f27e-1c2f-414e-83dd-9c2956ca652b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:17 GMT

