HTTP/1.1 302 
X-Request-Id: 8b2673b8-c2e9-4dc0-a47a-68c3f82e7e24
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:15 GMT

