HTTP/1.1 302 
X-Request-Id: d6e96483-1f3f-40fc-8ddb-af7b4d0e454a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:32 GMT

