HTTP/1.1 302 
X-Request-Id: fdacd1cc-02c9-4613-ab33-bebec142d70f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

