HTTP/1.1 302 
X-Request-Id: 3865d9ca-4754-41c0-ac10-2fbf52355519
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:05 GMT

