HTTP/1.1 302 
X-Request-Id: 8893012f-3412-4820-8a00-9d7521058f2b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:19 GMT

