HTTP/1.1 302 
X-Request-Id: 995e805b-da7c-460d-b815-b91588e17565
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

