HTTP/1.1 302 
X-Request-Id: 124149f6-be07-4b4a-9c09-1b940e34b0d1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

