HTTP/1.1 302 
X-Request-Id: 8505450f-1fae-4993-a2b0-2bc0a0fb0a5e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:15 GMT

