HTTP/1.1 302 
X-Request-Id: 21cf20ed-d686-4d20-bd19-57bc127aca21
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

