HTTP/1.1 302 
X-Request-Id: 66586ff8-447c-4ed9-80e6-6c7952b9f559
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

