HTTP/1.1 302 
X-Request-Id: 7489da57-b60e-4708-bbc5-5256b6d5e4da
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

