HTTP/1.1 302 
X-Request-Id: 7df401f6-cdcc-4a78-85f5-a77964ca7fbb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

