HTTP/1.1 302 
X-Request-Id: 0a595f28-2ed4-4e56-b898-d062dc96c2dd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:32 GMT

