HTTP/1.1 403 
X-Request-Id: ae5c47dd-3792-46ce-869d-b079ee6dd47a
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:22 GMT

{"instance":"urn:uuid:ae5c47dd-3792-46ce-869d-b079ee6dd47a","status":403,"title":"Forbidden"}