HTTP/1.1 302 
X-Request-Id: 111ae942-163e-40e1-8bc9-ea1eed930d82
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

