HTTP/1.1 302 
X-Request-Id: ee1a99c4-36a8-4566-930c-47541662e94a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

