HTTP/1.1 201 
X-Request-Id: f3194265-90c8-47b1-b52c-1fe4186f99d0
Location: /api/links/4fkrw6rA
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"4fkrw6rA","shortUrl":"http://localhost:8080/4fkrw6rA","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:24:00Z"}