HTTP/1.1 405 
X-Request-Id: ee38c09c-1d61-4a3e-a7c8-51616f172d9b
Allow: GET
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:10:46 GMT

{"instance":"urn:uuid:ee38c09c-1d61-4a3e-a7c8-51616f172d9b","status":405,"title":"Method Not Allowed"}