HTTP/1.1 429 
X-Request-Id: 9bee8f7a-4b62-498a-9498-c9c1b33a2dbc
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:15 GMT

{"instance":"urn:uuid:9bee8f7a-4b62-498a-9498-c9c1b33a2dbc","status":429,"title":"Too Many Requests"}