HTTP/1.1 429 
X-Request-Id: 28fe2c57-5a90-480c-adb9-b039daaf18ab
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"instance":"urn:uuid:28fe2c57-5a90-480c-adb9-b039daaf18ab","status":429,"title":"Too Many Requests"}