HTTP/1.1 302 
X-Request-Id: 933070a6-c32c-4edd-9d09-eb16b673aa62
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

