HTTP/1.1 302 
X-Request-Id: dc111d37-ba54-44b1-98c3-614986871bc2
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

