HTTP/1.1 302 
X-Request-Id: bbf09f1a-3cb8-4d98-a894-ea46b0a22de1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

