HTTP/1.1 302 
X-Request-Id: e10755db-3db9-49eb-957b-fba8dd380fe4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

