HTTP/1.1 302 
X-Request-Id: c795a450-8133-478d-949c-870ebc7eea74
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:08 GMT

