HTTP/1.1 302 
X-Request-Id: 975f239f-f424-4e33-b569-1e30ae00b78d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

