HTTP/1.1 302 
X-Request-Id: faa3b7ce-850c-4004-a2ae-5198af3a2f01
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:54 GMT

