HTTP/1.1 302 
X-Request-Id: f2219153-128d-4669-a639-aef1724f5798
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

