HTTP/1.1 201 
X-Request-Id: 0201e5c9-9e43-43a5-93d0-b6457ed824d0
Location: /api/links/UeJrtwwW
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:15 GMT

{"code":"UeJrtwwW","shortUrl":"http://localhost:8080/UeJrtwwW","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:32:00Z"}