HTTP/1.1 201 
X-Request-Id: b349a144-2d90-4902-bc4b-ea4aac78722c
Location: /api/links/zD5KzXLN
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"zD5KzXLN","shortUrl":"http://localhost:8080/zD5KzXLN","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:28:00Z"}