HTTP/1.1 302 
X-Request-Id: 633f12ae-6de0-42a5-8d2c-c26320dac4bc
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

