HTTP/1.1 201 
X-Request-Id: 4d91014e-f031-43d0-92bb-5098573d5856
Location: /api/links/1QLt0nSN
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:16 GMT

{"code":"1QLt0nSN","shortUrl":"http://localhost:8080/1QLt0nSN","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:36:00Z"}