HTTP/1.1 302 
X-Request-Id: ee66de7d-1558-46f1-9c61-012d5fb016fb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:17 GMT

