HTTP/1.1 302 
X-Request-Id: 71d8207c-0892-4523-805b-d6d2ce5fe59f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

