HTTP/1.1 302 
X-Request-Id: b5af785d-15cb-4e3c-af31-49ebea8698bd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

