HTTP/1.1 429 
X-Request-Id: 00c1069b-3fc1-47e3-b794-a5606bb0bc09
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:15 GMT

{"instance":"urn:uuid:00c1069b-3fc1-47e3-b794-a5606bb0bc09","status":429,"title":"Too Many Requests"}