HTTP/1.1 302 
X-Request-Id: 8418b484-5248-45ed-9dae-9b4877594495
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

