HTTP/1.1 302 
X-Request-Id: e3e0aa22-6069-4c77-80f0-a4533ae9b01e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

