HTTP/1.1 302 
X-Request-Id: 997259e4-240a-4edc-8806-7becefd7e549
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

