HTTP/1.1 302 
X-Request-Id: 440312dc-1480-4399-8b49-cb63fcb1500d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

