HTTP/1.1 302 
X-Request-Id: 5e49b4a3-85ad-45b3-a631-b831e3b8d6e8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

