HTTP/1.1 302 
X-Request-Id: eb5d0f85-43e7-40cc-8446-a81d6b91e62e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:16 GMT

