HTTP/1.1 429 
X-Request-Id: ef411894-2f63-4fa9-aa93-2892bcd296f9
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:17 GMT

{"instance":"urn:uuid:ef411894-2f63-4fa9-aa93-2892bcd296f9","status":429,"title":"Too Many Requests"}