HTTP/1.1 302 
X-Request-Id: 89908a9e-43b3-4374-95b4-550fae13fd52
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

