HTTP/1.1 302 
X-Request-Id: e0bb6382-5d0a-4fe9-b00f-9961972a31e4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

