HTTP/1.1 302 
X-Request-Id: 5bcfcded-8e75-4b7d-8d11-05b7bd247ac7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

