HTTP/1.1 302 
X-Request-Id: b48c2ee0-7bd4-42a8-843c-94a413f1b92b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

