HTTP/1.1 302 
X-Request-Id: 738176f9-cca6-47a2-81fa-14692424483b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

