HTTP/1.1 302 
X-Request-Id: 21767127-e816-4616-a228-c4b1b1101686
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

