HTTP/1.1 302 
X-Request-Id: 879f115b-cd72-4013-b77b-0003ed0a69b3
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

