HTTP/1.1 302 
X-Request-Id: 72d3acc0-a9ef-46ba-8777-354e7848818b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:32 GMT

