HTTP/1.1 302 
X-Request-Id: 44430441-c29d-4f09-ac07-ee106f4e1762
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:15 GMT

