HTTP/1.1 302 
X-Request-Id: 4d42b09a-cbd2-4130-9eb9-d598a432be01
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:05 GMT

