HTTP/1.1 302 
X-Request-Id: d3e94b16-4b5c-46ce-87f8-e371af632e2c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

