HTTP/1.1 302 
X-Request-Id: e12f6624-23d7-404e-9c7b-747b00e1c190
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:16 GMT

