HTTP/1.1 201 
X-Request-Id: 00342ca4-1fef-4dcb-b93d-ec0f14bd02c7
Location: /api/links/WHLKqwkE
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:14 GMT

{"code":"WHLKqwkE","shortUrl":"http://localhost:8080/WHLKqwkE","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:16:00Z"}