HTTP/1.1 302 
X-Request-Id: 5c51e4ac-feb7-4402-87c4-a65f24837b08
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:16 GMT

