HTTP/1.1 302 
X-Request-Id: fabe02c8-723e-4bc6-98cd-0699156155c5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

