HTTP/1.1 302 
X-Request-Id: b74959b2-45da-4f7d-be90-939688e861fe
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

