HTTP/1.1 302 
X-Request-Id: 878f59a6-2987-4c10-bc9d-611a9ab47a6a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

