HTTP/1.1 302 
X-Request-Id: 4f935d53-2142-4cc7-be87-11578d45d5e1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

