HTTP/1.1 302 
X-Request-Id: 16445f73-68ad-4cf7-a1c0-082a5aca50dd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:29 GMT

