HTTP/1.1 302 
X-Request-Id: 1bf32073-7cb2-4672-83ee-36e6263de33a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

