HTTP/1.1 302 
X-Request-Id: 374ab86e-bc93-4ffe-8a6e-f2ecaf29ed09
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:15 GMT

