HTTP/1.1 302 
X-Request-Id: 9da2a9d6-c908-4b2d-8fb8-95c8a5159c6c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

