HTTP/1.1 403 
X-Request-Id: 8ae0e89f-e437-4f0e-b6e3-d51034fbcb68
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:25 GMT

{"instance":"urn:uuid:8ae0e89f-e437-4f0e-b6e3-d51034fbcb68","status":403,"title":"Forbidden"}