HTTP/1.1 302 
X-Request-Id: 195474b3-e3e7-49a1-871b-165ebdf36484
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:56 GMT

