HTTP/1.1 302 
X-Request-Id: e9ac16f0-849e-442d-bf24-0471c1de1ca6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:16 GMT

