HTTP/1.1 302 
X-Request-Id: 5862f791-67ae-41f0-acb9-22326237ff1e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

