HTTP/1.1 302 
X-Request-Id: 89b178a3-976d-4562-8ad5-c53b41e90656
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

