HTTP/1.1 302 
X-Request-Id: 96dbfaf4-f9a2-4f72-9a62-8946766a2772
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

