HTTP/1.1 302 
X-Request-Id: b6c6b6bf-7ad8-4841-8d1f-c0cacc4c6e78
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

