HTTP/1.1 302 
X-Request-Id: 8493c0f9-ddd0-4e14-8a2e-f01f1d2f255b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:03 GMT

