HTTP/1.1 302 
X-Request-Id: ea155de1-295f-4b78-8263-7496519c0b92
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:58 GMT

