HTTP/1.1 302 
X-Request-Id: e179d151-4a3c-43f7-acd2-9ca88cd7d6f6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

