HTTP/1.1 302 
X-Request-Id: 2f6ac8cc-7356-4f3a-9b75-c850d70e4300
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:52 GMT

