HTTP/1.1 302 
X-Request-Id: 493046f1-572a-426b-9804-a678390ca0d1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

