HTTP/1.1 302 
X-Request-Id: a6faafb8-716b-4986-b135-37b40a3f64ec
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:14 GMT

