HTTP/1.1 302 
X-Request-Id: ee30ec55-981a-41f7-b973-732f493774c7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:00 GMT

