HTTP/1.1 302 
X-Request-Id: 65ef3332-d8fb-464b-86b6-20ab8c40e84f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

