HTTP/1.1 201 
X-Request-Id: 9624aa66-d4cc-444b-97a9-646550634571
Location: /api/links/4rWWBbTm
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:18 GMT

{"code":"4rWWBbTm","shortUrl":"http://localhost:8080/4rWWBbTm","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}