HTTP/1.1 302 
X-Request-Id: 81cf712c-b848-4145-8937-78d701200795
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

