HTTP/1.1 302 
X-Request-Id: c6da436b-a87e-4047-893f-60e7265a58cb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

