HTTP/1.1 302 
X-Request-Id: 41b959be-cb53-474e-87d8-11897bfc7055
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:09 GMT

