HTTP/1.1 302 
X-Request-Id: 6913ffea-1686-4a99-8fe1-6f269090eaf0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:55 GMT

