HTTP/1.1 302 
X-Request-Id: 28ad7f02-c089-438b-b4e2-0f188078cfe6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

