HTTP/1.1 302 
X-Request-Id: b865010d-9129-4aad-a5e9-106a779308cc
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:53 GMT

