HTTP/1.1 302 
X-Request-Id: 89a2552a-2e62-496d-be61-fd1d1b6c1960
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:07 GMT

