HTTP/1.1 302 
X-Request-Id: b2d1337c-4c72-42c8-87f8-1ccc251f708c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

