HTTP/1.1 302 
X-Request-Id: 2b7fab73-58f4-45c7-b9ba-86aff427666b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:04 GMT

