HTTP/1.1 302 
X-Request-Id: b57ecef9-b427-48c3-8819-0bba41cdd79b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:59 GMT

