HTTP/1.1 302 
X-Request-Id: 11e645cc-a622-4078-8662-b583ed59192b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:32 GMT

