HTTP/1.1 302 
X-Request-Id: e292b7fe-0b6c-4a1e-8fa9-37e777bca11e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:06 GMT

