HTTP/1.1 302 
X-Request-Id: f1ef1fd2-458c-4a60-86a7-cfabfe3c615f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:02 GMT

