HTTP/1.1 302 
X-Request-Id: aa1466d2-92e5-4200-8dec-c5049065a9ae
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:10:57 GMT

