HTTP/1.1 302 
X-Request-Id: bd6ab322-e6bd-411a-9c55-ac7b6e4d126e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:15 GMT

