HTTP/1.1 302 
X-Request-Id: 99abf316-b6b8-44a2-95b2-0c338f9a26c0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:29 GMT

