HTTP/1.1 302 
X-Request-Id: 782927b9-8443-4b6a-99ed-2ff1d55b1660
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:41 GMT

