HTTP/1.1 302 
X-Request-Id: aed5406e-218d-49aa-8573-e33c119d403d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

