HTTP/1.1 302 
X-Request-Id: d7cb7766-6c5e-402d-bed7-9b991f6b592f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

