HTTP/1.1 302 
X-Request-Id: 673c067e-8135-48c4-886e-1e4582970a95
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

