HTTP/1.1 302 
X-Request-Id: edaf8fe0-1e58-4e02-99c5-6e2597af9570
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

