HTTP/1.1 201 
X-Request-Id: 86edc434-e5a8-4a1a-9787-936934a554b5
Location: /api/links/AStSTOZb
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:07 GMT

{"code":"AStSTOZb","shortUrl":"http://localhost:8080/AStSTOZb","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:04:00Z"}