HTTP/1.1 302 
X-Request-Id: 0cb9d651-e0c9-47c1-bffe-e2bba3541e2c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

