HTTP/1.1 429 
X-Request-Id: 60c49e69-5771-4a4b-8f0c-627a25bb9d77
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:04 GMT

{"instance":"urn:uuid:60c49e69-5771-4a4b-8f0c-627a25bb9d77","status":429,"title":"Too Many Requests"}