HTTP/1.1 302 
X-Request-Id: a25f6734-9652-4403-85c7-a6dc25b2647f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

