HTTP/1.1 302 
X-Request-Id: 07ee9e6a-541a-40c0-91bf-f9eb89bed1e4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

