HTTP/1.1 302 
X-Request-Id: eacc5d43-6d00-4cc4-813d-f46a073dc9de
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

