HTTP/1.1 302 
X-Request-Id: fd572199-7583-4de4-bf16-2c988386a8eb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

