HTTP/1.1 302 
X-Request-Id: e3301250-c0c1-4e50-a859-f5605a19263d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

