HTTP/1.1 302 
X-Request-Id: 02bdd0ed-2908-4f68-b646-062cfcdfdd96
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

