HTTP/1.1 302 
X-Request-Id: 57586980-3b2f-4487-846e-ad232a94b9ea
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

