HTTP/1.1 302 
X-Request-Id: c1a2afbf-1cd9-4236-8c9a-11fde11577e2
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:04 GMT

