HTTP/1.1 302 
X-Request-Id: e86266d7-5ca9-47b7-9233-42f04f0c36fd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

