HTTP/1.1 302 
X-Request-Id: b809a6d8-b9cc-42c9-a7dc-60ea59916997
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

