HTTP/1.1 302 
X-Request-Id: b0fa3145-0988-4df0-ae60-1ed69752513f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

