HTTP/1.1 302 
X-Request-Id: 9fc716c9-6e79-4f12-bcba-d3fb82a315ae
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

