HTTP/1.1 302 
X-Request-Id: 8b29bc76-4cd0-482f-b4a1-9b37480c9143
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

