HTTP/1.1 302 
X-Request-Id: 24a1230b-c5b9-470e-b319-2665a189222e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

