HTTP/1.1 302 
X-Request-Id: ea739972-1619-48ea-afba-c4a7ea99ed7a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

