HTTP/1.1 302 
X-Request-Id: e2d73646-9c02-4fe4-a66e-e286728cb990
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

