HTTP/1.1 302 
X-Request-Id: a285aaaa-9561-430a-ac91-5d01e18155dc
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

