HTTP/1.1 302 
X-Request-Id: 150f1a55-db69-4f7a-9ca2-4fb285750c30
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

