HTTP/1.1 302 
X-Request-Id: 6e9d527d-8faa-4350-9971-93e04fa663c1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

