HTTP/1.1 302 
X-Request-Id: 302db1ab-29d1-40fc-adb7-360ca0b13a4e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

