HTTP/1.1 302 
X-Request-Id: 2c773947-7341-42f1-9b71-8aca98af3fea
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:58 GMT

