HTTP/1.1 302 
X-Request-Id: a090efa6-4500-4011-84a3-a27aca35c460
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

