HTTP/1.1 302 
X-Request-Id: 510e22bf-8ad9-4d74-a907-a24367d52983
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

