HTTP/1.1 302 
X-Request-Id: d56e2135-2bd0-4a97-aed3-911ed105faa6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

