HTTP/1.1 302 
X-Request-Id: b0bcd09b-bf5d-46ff-9e44-6f67af180fcb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

