HTTP/1.1 302 
X-Request-Id: 6a4e2eb7-ec7e-4fa7-97c2-792582302902
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:58 GMT

