HTTP/1.1 302 
X-Request-Id: 2b2eae72-4b86-45a9-a24c-57df49f7e88b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

