HTTP/1.1 302 
X-Request-Id: ec5ac4ec-23bd-4d66-b73a-397581498d95
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

