HTTP/1.1 302 
X-Request-Id: 73daa24a-6ba2-4f08-9315-11823e7be486
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

