HTTP/1.1 302 
X-Request-Id: ac1e0071-4b7e-4ca7-b3a4-cda4aa119d3d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

