HTTP/1.1 302 
X-Request-Id: 2108c37f-d0cc-4cb7-aad0-233c9ae7072e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

