HTTP/1.1 302 
X-Request-Id: 5b499687-c873-4417-9341-bbdd42b2ee52
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

