HTTP/1.1 302 
X-Request-Id: 96936c4e-38fa-4503-8120-4c3f49a17ef8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

