HTTP/1.1 302 
X-Request-Id: 891ef527-3ce4-4da3-bfb2-0f730ebade21
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

