HTTP/1.1 302 
X-Request-Id: ecb1fcfe-c27b-4174-9290-e9b926e1b840
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

