HTTP/1.1 302 
X-Request-Id: 398229e1-8ab4-4c65-bc63-b4d0a4e8e071
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

