HTTP/1.1 302 
X-Request-Id: 435a71c4-75cd-4de1-9370-b3c07bf07002
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

