HTTP/1.1 302 
X-Request-Id: ba535044-5499-424b-91fd-5e0907e2091a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

