HTTP/1.1 302 
X-Request-Id: 325133a8-8b12-4f84-a88f-e08d1d78a62e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

