HTTP/1.1 302 
X-Request-Id: d52ee0bf-b39c-452a-abba-539f60129849
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:08 GMT

