HTTP/1.1 302 
X-Request-Id: b06a4502-2cb6-4f17-8969-bfc0e685ef4c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

