HTTP/1.1 302 
X-Request-Id: 5b9a54ee-64f2-4ef8-95cc-1b122710ec13
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

