HTTP/1.1 302 
X-Request-Id: 32c0d6ba-2a2b-4aae-ae18-3d37e481573f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

