HTTP/1.1 302 
X-Request-Id: 8dc204d3-0501-48f2-8b27-50aa6444d296
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

