HTTP/1.1 302 
X-Request-Id: 8af5064e-4c96-4dff-abc7-5b38f87320dd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

