HTTP/1.1 201 
X-Request-Id: ee5fea5a-3e5a-42f6-b608-10e049b53ee0
Location: /api/links/A1Zm5fxO
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:07 GMT

{"code":"A1Zm5fxO","shortUrl":"http://localhost:8080/A1Zm5fxO","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:52:00Z"}