HTTP/1.1 200 
X-Request-Id: e1e22171-4134-4222-abab-aa5293b0ae1a
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 156
Date: Sun, 04 Oct 2026 02:12:21 GMT

{"availableTags":[],"description":"Clicks written to the click store","measurements":[{"statistic":"COUNT","value":21.0}],"name":"urlshort.clicks.recorded"}