HTTP/1.1 302 
X-Request-Id: a36e7923-6bd3-4452-88d4-2b17cd9997f9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

