HTTP/1.1 302 
X-Request-Id: 1fa11c42-40f5-421d-ae50-94eb3c9ae7c9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

