HTTP/1.1 302 
X-Request-Id: 3478ecbf-ab35-42be-8199-f576ddc03787
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

