HTTP/1.1 302 
X-Request-Id: 9fb45fcd-fb92-4a2a-832e-c4a93a9bc2ca
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

