HTTP/1.1 302 
X-Request-Id: 250aa530-f3a1-4b75-9520-bff865ac385a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

