HTTP/1.1 302 
X-Request-Id: 23ec8615-5af9-4053-89a8-e70127a5fd0a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

