HTTP/1.1 302 
X-Request-Id: 14ffcae9-1c91-4237-a771-0d68553137a7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

