HTTP/1.1 302 
X-Request-Id: ae9e2068-c442-4eee-b37b-7dabb35d6778
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

