HTTP/1.1 302 
X-Request-Id: 097b6537-284d-440c-822c-b6c88ea3bc9b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

