HTTP/1.1 302 
X-Request-Id: 7958bda8-d50b-4d97-bdfa-67cd7adf3ab9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

