HTTP/1.1 201 
X-Request-Id: 9aee5809-a916-48c9-a834-59de6df5ff03
Location: /api/links/Wbxto4SQ
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:05 GMT

{"code":"Wbxto4SQ","shortUrl":"http://localhost:8080/Wbxto4SQ","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:28:00Z"}