HTTP/1.1 302 
X-Request-Id: e6cc6b63-f365-408c-92f7-a4b729c52ff8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

