HTTP/1.1 403 
X-Request-Id: ab3ccddd-64a3-418c-9cae-018705a0be95
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:ab3ccddd-64a3-418c-9cae-018705a0be95","status":403,"title":"Forbidden"}