HTTP/1.1 302 
X-Request-Id: eb06d287-62b6-44b5-9d85-f19d3a132502
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

