HTTP/1.1 302 
X-Request-Id: a45a9f79-61ec-4531-a779-f4dbea23ddfc
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

