HTTP/1.1 302 
X-Request-Id: e102734e-e16f-4c68-adf0-a13925449f4d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

