HTTP/1.1 429 
X-Request-Id: 2886068a-980e-4bc2-8fa7-ffa050f9c684
Retry-After: 1
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:58 GMT

{"instance":"urn:uuid:2886068a-980e-4bc2-8fa7-ffa050f9c684","status":429,"title":"Too Many Requests"}