HTTP/1.1 302 
X-Request-Id: 1cbfd60a-a9e0-41b9-a67e-64bb03bc0937
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:04 GMT

