HTTP/1.1 302 
X-Request-Id: 546d0d77-e167-491a-8367-2c158fd1af96
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

