HTTP/1.1 302 
X-Request-Id: 3c0bc339-b570-4711-b01f-74e0dcf992bd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

