HTTP/1.1 302 
X-Request-Id: 986d5d36-1f2c-43f7-b16f-b8d090cedb26
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:08 GMT

