HTTP/1.1 302 
X-Request-Id: 55b61335-73be-4de6-b555-5ebb427c06dd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:06 GMT

