HTTP/1.1 302 
X-Request-Id: b06a6f84-e402-4388-8331-3511a35147e9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:05 GMT

