HTTP/1.1 302 
X-Request-Id: 95884938-483c-4555-82b0-e2cceb1b290c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

