HTTP/1.1 302 
X-Request-Id: 14c8213c-6fc4-44c4-bfe1-958993de0b62
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

