HTTP/1.1 302 
X-Request-Id: 8b75b38f-9337-4b8a-ba99-c6a6d9579abb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

