HTTP/1.1 302 
X-Request-Id: ff3c8c92-ef00-418e-a4da-3b04a3ce9f16
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

