HTTP/1.1 201 
X-Request-Id: 72b4e107-e522-4d9c-afe6-989afe29ab84
Location: /api/links/V3CLH5PT
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:04 GMT

{"code":"V3CLH5PT","shortUrl":"http://localhost:8080/V3CLH5PT","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:16:00Z"}