HTTP/1.1 302 
X-Request-Id: 83fa46a2-8549-4ea9-9cfa-118e8f0310e7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

