HTTP/1.1 403 
X-Request-Id: a844d58b-ea01-4c41-b293-30448a61591d
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:16 GMT

{"instance":"urn:uuid:a844d58b-ea01-4c41-b293-30448a61591d","status":403,"title":"Forbidden"}