HTTP/1.1 302 
X-Request-Id: 822b3275-36ab-41a2-9692-3e86153969d3
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:06 GMT

