HTTP/1.1 403 
X-Request-Id: a428bed0-6a99-4e96-a789-5aaba435456f
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:a428bed0-6a99-4e96-a789-5aaba435456f","status":403,"title":"Forbidden"}