HTTP/1.1 302 
X-Request-Id: 20610be7-7ea7-4012-a3d9-2b39208a4a2e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

