HTTP/1.1 302 
X-Request-Id: 81b2e531-7fb0-4f9e-98e7-a078076da8bb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

