HTTP/1.1 302 
X-Request-Id: a252dd61-c7db-4608-8266-597dbf193715
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

