HTTP/1.1 410 
X-Request-Id: 539cc718-68ce-4ea1-a87d-ab19c9d95005
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:35 GMT

{"instance":"urn:uuid:539cc718-68ce-4ea1-a87d-ab19c9d95005","status":410,"title":"Gone"}