HTTP/1.1 302 
X-Request-Id: 42567cc5-6d03-426d-a253-a6685fe8f8ef
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:07 GMT

