HTTP/1.1 201 
X-Request-Id: 86efc31c-51d6-4551-8b68-0b8e0719f16c
Location: /api/links/ozYRfj7r
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:08 GMT

{"code":"ozYRfj7r","shortUrl":"http://localhost:8080/ozYRfj7r","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:28:00Z"}