HTTP/1.1 302 
X-Request-Id: 9c0f2c2e-8050-43f9-b52b-0a257409585b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

