HTTP/1.1 302 
X-Request-Id: 7431b0b5-501a-4444-843a-41bf43e81f7c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

