HTTP/1.1 302 
X-Request-Id: 2d2d0999-54bb-4df9-8de7-e73c362db8d5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

