HTTP/1.1 302 
X-Request-Id: bb687795-ceba-4349-b57a-2bc4c057fa59
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

