HTTP/1.1 302 
X-Request-Id: 01ac6faf-1c6b-4e30-a97b-eb9ac00890de
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

