HTTP/1.1 429 
X-Request-Id: 14672cb2-493f-487b-b1cf-ac8cb35a8ec2
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:07 GMT

{"instance":"urn:uuid:14672cb2-493f-487b-b1cf-ac8cb35a8ec2","status":429,"title":"Too Many Requests"}