HTTP/1.1 302 
X-Request-Id: 27a0dda5-7322-485e-8741-a91f4b107b8e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

