HTTP/1.1 302 
X-Request-Id: 03dc6b4d-8e38-45c7-abe1-5f8c093f5eb4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

