HTTP/1.1 302 
X-Request-Id: 5cfbc7cf-6b10-4cb8-b9bd-e0196269f103
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

