HTTP/1.1 302 
X-Request-Id: e2435af1-a640-4220-b55c-af965fe25362
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

