HTTP/1.1 302 
X-Request-Id: 8383907c-5bdb-4785-b152-cd59e598dc39
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:05 GMT

