HTTP/1.1 302 
X-Request-Id: c7ff6c45-2b52-49e1-84ff-2d66700c4a35
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

