HTTP/1.1 302 
X-Request-Id: 10307ab0-23e6-4d01-b193-d0c235026770
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

