HTTP/1.1 302 
X-Request-Id: 72844be8-8401-4ad8-a560-18d87deeb7b6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

