HTTP/1.1 302 
X-Request-Id: d357babe-d2a7-4450-bfdf-3affe8b4b6c1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:07 GMT

