HTTP/1.1 302 
X-Request-Id: a39162d9-16e6-4ce0-b7c7-82ee8459085a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

