HTTP/1.1 302 
X-Request-Id: 1b354315-1dff-495f-8e45-06d8683fc00b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

