HTTP/1.1 302 
X-Request-Id: 14b6ef01-b3f0-4bcd-8c52-59ca510baacd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

