HTTP/1.1 302 
X-Request-Id: cf5ce4e1-aec8-4ee6-888c-5e45ed057122
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

