HTTP/1.1 429 
X-Request-Id: 6816cfdf-6f81-4e50-8de0-858def8c20d4
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:04 GMT

{"instance":"urn:uuid:6816cfdf-6f81-4e50-8de0-858def8c20d4","status":429,"title":"Too Many Requests"}