HTTP/1.1 302 
X-Request-Id: 9bf60c1c-dc3c-46f8-b7e0-5a1ad3e9a977
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

