HTTP/1.1 302 
X-Request-Id: d7527219-f76e-433b-a97d-26d2821d4d00
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

