HTTP/1.1 302 
X-Request-Id: 2096e88f-3681-4646-a366-42c05421ed86
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

