HTTP/1.1 302 
X-Request-Id: 0913e343-144e-422d-889a-45943ea46c2c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

