HTTP/1.1 302 
X-Request-Id: 67a811ef-4303-481b-b9c3-dae70d1efa03
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

