HTTP/1.1 302 
X-Request-Id: 039ecea8-ff03-436f-8c42-f43be0da1a64
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

