HTTP/1.1 429 
X-Request-Id: 448a04f7-9ad2-4e02-b1dc-9a9991d75b72
Retry-After: 1
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:11:37 GMT

{"instance":"urn:uuid:448a04f7-9ad2-4e02-b1dc-9a9991d75b72","status":429,"title":"Too Many Requests"}