HTTP/1.1 429 
X-Request-Id: e13782f2-278e-40d0-9fce-4d22a2133d39
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:04 GMT

{"instance":"urn:uuid:e13782f2-278e-40d0-9fce-4d22a2133d39","status":429,"title":"Too Many Requests"}