HTTP/1.1 302 
X-Request-Id: 1a3a3e2f-b582-4f28-8ac2-ecf40c91da78
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

