HTTP/1.1 429 
X-Request-Id: 667257d0-f6ec-4b3a-9e58-2deecd4f062b
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:05 GMT

{"instance":"urn:uuid:667257d0-f6ec-4b3a-9e58-2deecd4f062b","status":429,"title":"Too Many Requests"}