HTTP/1.1 302 
X-Request-Id: 98dc24e0-bfbd-467f-b7ff-65001f9be61a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

