HTTP/1.1 302 
X-Request-Id: 49c09aa2-0aa6-4fd6-8ddc-1ecb7dad92a0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

