HTTP/1.1 302 
X-Request-Id: 7c2536f1-ac09-4f3a-9acd-a5ccb6b6ebd9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

