HTTP/1.1 302 
X-Request-Id: b00aa9a4-f2e8-4e28-806b-2ea08d75be49
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

