HTTP/1.1 302 
X-Request-Id: 1a16d8f2-9714-4e5e-8426-dd6b6749a62a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

