HTTP/1.1 403 
X-Request-Id: 9399e613-0800-411c-b5fc-55acaf0ca667
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:9399e613-0800-411c-b5fc-55acaf0ca667","status":403,"title":"Forbidden"}