HTTP/1.1 302 
X-Request-Id: be08d6a3-3566-4dc2-9522-0220da8ec1d1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

