HTTP/1.1 200 
X-Request-Id: 75d8706d-d2b8-4e2d-9c27-a2d5272425b8
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 155
Date: Sun, 04 Oct 2026 02:12:21 GMT

{"availableTags":[],"description":"Clicks reported by a click lost event","measurements":[{"statistic":"COUNT","value":1.0}],"name":"urlshort.clicks.lost"}