HTTP/1.1 302 
X-Request-Id: 7ce8829a-b141-4602-b7cf-21ef7be3cf0e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

