HTTP/1.1 302 
X-Request-Id: b2e0f35b-b954-48f2-9d61-624156967f3a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

