HTTP/1.1 201 
X-Request-Id: bc905845-5aff-47c2-b753-8e77d3ada63a
Location: /api/links/n71Wl4ed
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:06 GMT

{"code":"n71Wl4ed","shortUrl":"http://localhost:8080/n71Wl4ed","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:48:00Z"}