HTTP/1.1 302 
X-Request-Id: aa1529c9-ba5d-4dfd-919d-a679852e068b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:07 GMT

