HTTP/1.1 302 
X-Request-Id: 3c2bae44-7946-44f1-822f-cefb17b74aba
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

