HTTP/1.1 302 
X-Request-Id: c3430a59-00be-44e1-950d-36791fbc551d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

