HTTP/1.1 302 
X-Request-Id: 039bd2a4-c5ff-4885-a51c-57668a207732
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

