HTTP/1.1 302 
X-Request-Id: dad58872-eeb5-4184-badc-d7f08f50232d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

