HTTP/1.1 403 
X-Request-Id: 2b0a1981-66e5-482f-9cae-4ad0ad8fc2fb
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:2b0a1981-66e5-482f-9cae-4ad0ad8fc2fb","status":403,"title":"Forbidden"}