HTTP/1.1 302 
X-Request-Id: 8c6fcf8f-9499-48ec-84f9-ce3fd04188e6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

