HTTP/1.1 302 
X-Request-Id: 08cd4ec5-9669-4b19-9169-06dec534dd41
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:58 GMT

