HTTP/1.1 302 
X-Request-Id: d23243c4-1de9-47f6-9531-f5eb06dde678
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

