HTTP/1.1 302 
X-Request-Id: 8d3a0ce6-2eb9-4044-b0a4-2082d2e30046
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

