HTTP/1.1 302 
X-Request-Id: e7272736-c8d0-45b0-9743-a1da927e4da0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

