HTTP/1.1 302 
X-Request-Id: 8ff9b7c2-2888-42ce-8619-3dccf723818f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

