HTTP/1.1 302 
X-Request-Id: 080404f4-9412-4736-ac75-027b6e389032
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

