HTTP/1.1 302 
X-Request-Id: 7a14cb71-94d8-4a0f-8bcc-717e5bbc44d8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

