HTTP/1.1 302 
X-Request-Id: e88cf1a1-ca1e-4a92-b12d-e4e0e120fdf0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

