HTTP/1.1 302 
X-Request-Id: 41e91f3e-8c59-42f3-8c0f-d2cac3dfe17e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

