HTTP/1.1 302 
X-Request-Id: dd5dd9b9-d8ca-459c-9dd1-905ba1689569
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

