HTTP/1.1 302 
X-Request-Id: 47cba9c1-8f99-4622-80ab-d76e5ca30d0a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:58 GMT

