HTTP/1.1 302 
X-Request-Id: 5e6cf3a0-68db-444e-880f-2098f4cfdf33
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

