HTTP/1.1 403 
X-Request-Id: b11462ba-7bb8-41e0-abb5-09ab38be6130
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:b11462ba-7bb8-41e0-abb5-09ab38be6130","status":403,"title":"Forbidden"}