HTTP/1.1 302 
X-Request-Id: c5c17bfd-b7d4-4322-9b58-3f752f33e701
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

