HTTP/1.1 302 
X-Request-Id: a81a9ad7-03d0-4a13-b868-4c9265e83b29
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

