HTTP/1.1 302 
X-Request-Id: 04791c23-7a2c-4150-a278-037c0e48d67c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

