HTTP/1.1 302 
X-Request-Id: 77a500a9-c756-467f-a5e3-cc618be1e7e1
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

