HTTP/1.1 302 
X-Request-Id: 74b488c0-da83-4ecf-974e-598b3a72247b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

