HTTP/1.1 201 
X-Request-Id: 83828f79-9956-4a44-8416-1776cb8366b4
Location: /api/links/zAmKOpEO
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:05 GMT

{"code":"zAmKOpEO","shortUrl":"http://localhost:8080/zAmKOpEO","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:32:00Z"}