HTTP/1.1 403 
X-Request-Id: ec49e7da-8b81-4ba6-9ab4-2becf458cc91
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:ec49e7da-8b81-4ba6-9ab4-2becf458cc91","status":403,"title":"Forbidden"}