HTTP/1.1 302 
X-Request-Id: c5c6807a-2e4e-45e4-ad01-4b07c1483c25
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

