HTTP/1.1 302 
X-Request-Id: 2e7d596d-d5f5-4d2f-961b-79bf3abab0de
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

