HTTP/1.1 302 
X-Request-Id: 57a20a9e-11ea-485d-ac35-1b22bd696b1e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

