HTTP/1.1 302 
X-Request-Id: 5217457b-b94a-4def-a05f-5ba5159e2186
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

