HTTP/1.1 302 
X-Request-Id: 46475387-3efb-453d-b704-aadf7fe7e16a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

