HTTP/1.1 302 
X-Request-Id: 7c1570a3-d22e-4606-9bfb-4d227388ae2b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

