HTTP/1.1 403 
X-Request-Id: 8e5dcb20-881e-4c09-956d-8fae825d6a4b
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:16 GMT

{"instance":"urn:uuid:8e5dcb20-881e-4c09-956d-8fae825d6a4b","status":403,"title":"Forbidden"}