HTTP/1.1 429 
X-Request-Id: 62e22127-12b2-40f8-b44f-ae4c482bf4b6
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:07 GMT

{"instance":"urn:uuid:62e22127-12b2-40f8-b44f-ae4c482bf4b6","status":429,"title":"Too Many Requests"}