HTTP/1.1 302 
X-Request-Id: ef599647-4e48-4eaa-b206-e0131c7afeec
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

