HTTP/1.1 302 
X-Request-Id: 7d883117-ee76-4ffb-b4ec-8bb60dedafd8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

