HTTP/1.1 302 
X-Request-Id: 5ee6704a-efec-4746-972c-04c8ec6a9ced
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

