HTTP/1.1 302 
X-Request-Id: c9762df6-7e22-4e35-876c-8474ddaa797c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

