HTTP/1.1 302 
X-Request-Id: c109af94-d8e6-4ae8-8526-b89e718764c5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

