HTTP/1.1 302 
X-Request-Id: f2be015d-b6f4-40de-a0a2-38e1942aabe2
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

