HTTP/1.1 302 
X-Request-Id: d4a2dcf8-1377-4684-b73b-b2a1d0182dc6
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

