HTTP/1.1 302 
X-Request-Id: 8c993e7c-e870-46e4-858a-bc50443ae02d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

