HTTP/1.1 302 
X-Request-Id: d5d082bb-d710-42a6-98b2-24a07b5dcfad
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

