HTTP/1.1 302 
X-Request-Id: 609e1555-d911-4f85-9902-02e553c80a3a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

