HTTP/1.1 302 
X-Request-Id: 12e36192-d098-46ed-b572-77ac0f9217f0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

