HTTP/1.1 302 
X-Request-Id: 2d3d6332-d0ad-4eb7-bdd1-b4ac9f209c70
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

