HTTP/1.1 302 
X-Request-Id: 20a09989-dbb5-4585-a085-e6bfdc222686
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

