HTTP/1.1 302 
X-Request-Id: ef9c2935-74be-410f-b589-1297bca31794
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

