HTTP/1.1 302 
X-Request-Id: 044ddaa2-6d49-41ac-9236-8d0ffd2e66a5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

