HTTP/1.1 302 
X-Request-Id: 7d27e98d-8a35-4bda-9364-481c0ac95c7d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

