HTTP/1.1 302 
X-Request-Id: 9e5a1a27-0a81-47f2-a498-ba395c259616
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

