HTTP/1.1 302 
X-Request-Id: bac8461a-a621-4ee0-8671-79ffb17cff1f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

