HTTP/1.1 302 
X-Request-Id: 5d17ce7a-0bc4-4ba8-bd7a-c8be955a3a96
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

