HTTP/1.1 429 
X-Request-Id: a94f3567-aff7-465b-a424-8c74af9f1bcb
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:09 GMT

{"instance":"urn:uuid:a94f3567-aff7-465b-a424-8c74af9f1bcb","status":429,"title":"Too Many Requests"}