HTTP/1.1 201 
X-Request-Id: 88f273d9-3a1d-45a7-add7-c8f83f472c96
Location: /api/links/C1DXx9pu
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:05 GMT

{"code":"C1DXx9pu","shortUrl":"http://localhost:8080/C1DXx9pu","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:24:00Z"}