HTTP/1.1 201 
X-Request-Id: 639d08ff-e692-4608-ab4e-f4bbb503b22b
Location: /api/links/A2SzOLFw
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:06 GMT

{"code":"A2SzOLFw","shortUrl":"http://localhost:8080/A2SzOLFw","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:44:00Z"}