HTTP/1.1 302 
X-Request-Id: 4180af2b-f177-43a9-9cda-0ffd9df67e1f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

