HTTP/1.1 302 
X-Request-Id: db628a7b-5ab3-4b65-baeb-aee9bb5299ef
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

