HTTP/1.1 302 
X-Request-Id: 60ac1ca9-bab3-444d-80ef-0fda82848a9f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

