HTTP/1.1 302 
X-Request-Id: d91b3fb4-9834-48be-814a-17c4daf69db0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

