HTTP/1.1 302 
X-Request-Id: 4efc6984-0a5f-4ef2-8c1d-60f3d16a86e2
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:07 GMT

