HTTP/1.1 302 
X-Request-Id: 37fb9d9a-fcc1-4023-a008-2a8f19d32954
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:45 GMT

