HTTP/1.1 302 
X-Request-Id: accc058c-92d2-4be3-a8b0-38036fe40236
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:05 GMT

