HTTP/1.1 302 
X-Request-Id: 46db62c6-eaee-4308-b7ca-5f33caf2db8d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:07 GMT

