HTTP/1.1 201 
X-Request-Id: c8744cbe-9277-443a-b52e-49f46f6eca2e
Location: /api/links/H3X6iyYf
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:07 GMT

{"code":"H3X6iyYf","shortUrl":"http://localhost:8080/H3X6iyYf","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:04:00Z"}