HTTP/1.1 302 
X-Request-Id: 2d30a456-734a-4e08-8955-71e1fe09d09e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

