HTTP/1.1 200 
X-Request-Id: 54357616-a83b-40cb-bba0-561354b29a8b
Content-Type: application/json
Content-Length: 181
Date: Sun, 04 Oct 2026 02:12:04 GMT

{"code":"EckDk29c","totalClicks":3,"clicksPerDay":[{"date":"2026-10-01","clicks":3,"uniqueVisitors":2,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":3}]}