HTTP/1.1 429 
X-Request-Id: 8f1ab273-e083-48de-ae91-25dc14d627e8
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 02:12:06 GMT

{"instance":"urn:uuid:8f1ab273-e083-48de-ae91-25dc14d627e8","status":429,"title":"Too Many Requests"}