HTTP/1.1 302 
X-Request-Id: 290dcb9f-2d2e-450b-b86b-4d2f9b150324
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

