HTTP/1.1 302 
X-Request-Id: ae5f8560-3ce6-412d-a20b-62b62f0b5137
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

