HTTP/1.1 302 
X-Request-Id: c3bb3ae8-f265-444b-a29c-9f965b04c088
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

