HTTP/1.1 403 
X-Request-Id: 409faf6c-7fac-4157-a755-8adb83030909
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:09 GMT

{"instance":"urn:uuid:409faf6c-7fac-4157-a755-8adb83030909","status":403,"title":"Forbidden"}