HTTP/1.1 302 
X-Request-Id: c23d049e-d5ac-4e91-be03-c89f5e077f89
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

