HTTP/1.1 302 
X-Request-Id: 8173b707-03d7-4f2e-bda3-26aa9e30a962
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

