HTTP/1.1 302 
X-Request-Id: 8a735f4e-838e-4f31-b654-c5b7c2fc03b5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

