HTTP/1.1 302 
X-Request-Id: 00046a02-7e3e-44dc-9664-1789bd6cd8e0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

