HTTP/1.1 302 
X-Request-Id: 18c0aee0-abd5-49d3-9443-4828d9f077ce
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

