HTTP/1.1 302 
X-Request-Id: 7bf67713-67cb-424c-8f2d-d79126800bd8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:05 GMT

