HTTP/1.1 302 
X-Request-Id: a1423c36-38eb-48cc-bae9-dd3525ba60cf
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

