HTTP/1.1 302 
X-Request-Id: ebfcffed-57bb-4b87-87cf-4795ff00ee6e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

