HTTP/1.1 302 
X-Request-Id: 02fd4816-bcff-4b74-9540-d4887bed3401
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

