HTTP/1.1 201 
X-Request-Id: 222fa724-f2f4-4395-b593-2a9e42f113b4
Location: /api/links/sUnWRPMc
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:08 GMT

{"code":"sUnWRPMc","shortUrl":"http://localhost:8080/sUnWRPMc","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}