HTTP/1.1 302 
X-Request-Id: 29e679f5-8a2f-487e-a57d-a533ddedb873
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

