HTTP/1.1 302 
X-Request-Id: 58204671-9507-4342-aee4-1f33e9e6e66e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

