HTTP/1.1 302 
X-Request-Id: a2b01caf-700f-4398-aef2-a3f1f91158ac
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

