HTTP/1.1 201 
X-Request-Id: 474b4937-b840-4e97-8b2c-0868f4619327
Location: /api/links/sKLkiyZp
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:08 GMT

{"code":"sKLkiyZp","shortUrl":"http://localhost:8080/sKLkiyZp","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}