HTTP/1.1 302 
X-Request-Id: 8b989a97-c8de-49e6-8f51-d591ade9c06e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

