HTTP/1.1 201 
X-Request-Id: e5d4dc34-ce0a-4df7-bc62-2adc746bd47c
Location: /api/links/bAKHmhfX
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:34 GMT

{"code":"bAKHmhfX","shortUrl":"http://localhost:8080/bAKHmhfX","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:02:00Z"}