HTTP/1.1 302 
X-Request-Id: 75438590-d0d6-44be-8d3a-11dc6a63d94e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

