HTTP/1.1 302 
X-Request-Id: 34b2b7cf-b956-478c-ad9e-5c4aa5307c8d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

