HTTP/1.1 302 
X-Request-Id: 4c882078-f69a-40ca-ac11-1bc9cbf033e7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:47 GMT

