HTTP/1.1 403 
X-Request-Id: 40a1ff03-fec0-4dcd-b535-5db0b8c82469
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:16 GMT

{"instance":"urn:uuid:40a1ff03-fec0-4dcd-b535-5db0b8c82469","status":403,"title":"Forbidden"}