HTTP/1.1 302 
X-Request-Id: 1fac9f50-63f7-4a53-8a24-07fd71880cfd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:50 GMT

