HTTP/1.1 302 
X-Request-Id: 292d08cc-4b88-428b-aec8-8e2bceabd309
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:07 GMT

