HTTP/1.1 201 
X-Request-Id: 3760c177-745d-4ae5-8dc4-fb0b23151884
Location: /api/links/EckDk29c
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:04 GMT

{"code":"EckDk29c","shortUrl":"http://localhost:8080/EckDk29c","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:12:00Z"}