HTTP/1.1 302 
X-Request-Id: 9e0353f1-1f74-4715-bcfe-a9ca2f20f6f5
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:06 GMT

