HTTP/1.1 302 
X-Request-Id: 0a538050-07ff-498e-b16b-a3c46830526f
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

