HTTP/1.1 302 
X-Request-Id: 0c6fe9a9-f3fe-4996-82f7-c2c48b8ab850
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

