HTTP/1.1 200 
X-Request-Id: 78229a56-755c-45b1-9faf-f34219fac78f
Content-Type: application/json
Content-Length: 184
Date: Sun, 04 Oct 2026 02:12:18 GMT

{"code":"XiSNotLp","totalClicks":21,"clicksPerDay":[{"date":"2026-10-01","clicks":21,"uniqueVisitors":1,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":21}]}