HTTP/1.1 302 
X-Request-Id: ff52ca1f-b494-4eb0-a5ab-d1fc9b8a5d69
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

