HTTP/1.1 302 
X-Request-Id: e9a6dd2e-bd96-479e-9f91-47782a7b630b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

