HTTP/1.1 302 
X-Request-Id: 3317a808-6a39-4b2d-a200-b3d9160e962d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

