HTTP/1.1 302 
X-Request-Id: 9a3a23d9-0cc6-49d5-b087-f8e49f62a717
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

