HTTP/1.1 302 
X-Request-Id: 58b635a9-13d1-48a3-97d1-c5f2d2870581
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

