HTTP/1.1 302 
X-Request-Id: bc850437-0db1-403c-9aa7-72a18fd90ab0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

