HTTP/1.1 302 
X-Request-Id: ce630e11-8c3d-4dec-b9c0-7d1f53454748
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

