HTTP/1.1 302 
X-Request-Id: 1a36a179-3d71-48b6-86e2-a3354d9bf33b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:41 GMT

