HTTP/1.1 302 
X-Request-Id: e326fea9-960c-40a0-bed0-1be8219b0ade
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

