HTTP/1.1 302 
X-Request-Id: 43867df6-838a-46b7-871b-fb4fbe68ad55
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:04 GMT

