HTTP/1.1 302 
X-Request-Id: d28637da-862c-411f-9171-7389e424e3f0
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

