HTTP/1.1 302 
X-Request-Id: 5121e177-353c-4a65-94d5-34f8702c16e4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

