HTTP/1.1 302 
X-Request-Id: 294b26b2-656f-4ac0-85e3-53cb1d59199e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

