HTTP/1.1 302 
X-Request-Id: 148dc41e-1f63-41bc-a4bf-08cf45a21d68
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

