HTTP/1.1 302 
X-Request-Id: 399dab3c-e13c-417d-9f5d-7f7a62d163d4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

