HTTP/1.1 201 
X-Request-Id: 73f69afe-0ced-4b48-9cd1-2c776eb4b754
Location: /api/links/AAQumBY7
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:08 GMT

{"code":"AAQumBY7","shortUrl":"http://localhost:8080/AAQumBY7","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:12:00Z"}