HTTP/1.1 200 
X-Request-Id: c0748bfb-f364-4310-84c8-6c26954ab9f1
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 155
Date: Sun, 04 Oct 2026 02:12:18 GMT

{"availableTags":[],"description":"Clicks reported by a click lost event","measurements":[{"statistic":"COUNT","value":1.0}],"name":"urlshort.clicks.lost"}