HTTP/1.1 302 
X-Request-Id: eb8b72ce-9cfd-4b99-9e73-69a052e52596
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

