HTTP/1.1 302 
X-Request-Id: b3c42c10-b343-4a39-a182-5b6124626e42
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

