HTTP/1.1 302 
X-Request-Id: ef65af9b-6808-44f5-a818-5f65178c9915
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

