HTTP/1.1 201 
X-Request-Id: 810fca7a-1acb-4aaa-a466-6d84d2a16e40
Location: /api/links/qlA56jgy
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:11:35 GMT

{"code":"qlA56jgy","shortUrl":"http://localhost:8080/qlA56jgy","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:04:00Z"}