HTTP/1.1 302 
X-Request-Id: 29933220-46af-4b31-b9ad-15c6eea31c89
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

