HTTP/1.1 302 
X-Request-Id: 881cffdf-562b-4a8d-9431-f598d6c8d099
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:21 GMT

