HTTP/1.1 302 
X-Request-Id: 227d11b8-d712-4c4c-a397-9c2934c986eb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

