HTTP/1.1 302 
X-Request-Id: 0f837e45-d045-413c-b16f-c09cf3f7ca8a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

