HTTP/1.1 302 
X-Request-Id: d4d49069-1288-4136-b76f-a9a8ea81d39e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

