HTTP/1.1 302 
X-Request-Id: 4dc3b963-a346-426f-ac82-9dd3f128509b
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

