HTTP/1.1 302 
X-Request-Id: afb9f456-e45a-4f5d-9f0e-9869454e28e7
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

