HTTP/1.1 302 
X-Request-Id: 65850f37-7b1a-4721-b234-49e77421c5d8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

