HTTP/1.1 302 
X-Request-Id: eb489702-fa9d-442c-903c-5bdad882f8d4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

