HTTP/1.1 302 
X-Request-Id: e743b907-4e33-4a97-99d9-7e641fdf29cf
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:56 GMT

