HTTP/1.1 302 
X-Request-Id: 0f26ac8a-06a0-41ed-9350-a31cd72fc2cd
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

