HTTP/1.1 302 
X-Request-Id: 1cedd031-677d-4f2c-a1d6-604564bcb68d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:49 GMT

