HTTP/1.1 302 
X-Request-Id: 21bdbe59-7e66-4351-83fc-e51383354f8d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:48 GMT

