HTTP/1.1 302 
X-Request-Id: 0894170b-e1e1-4b82-9580-4e61c409238c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

