HTTP/1.1 302 
X-Request-Id: b673322d-61c1-467b-84d5-41eabf19388c
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

