HTTP/1.1 403 
X-Request-Id: f56b8e1d-68c4-45fd-a5c9-a32454decc23
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:15 GMT

{"instance":"urn:uuid:f56b8e1d-68c4-45fd-a5c9-a32454decc23","status":403,"title":"Forbidden"}