HTTP/1.1 302 
X-Request-Id: ecdb68e6-2d32-456a-9a3b-5fc12669d90a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:46 GMT

