HTTP/1.1 302 
X-Request-Id: 79ca5aaa-d3bb-45a9-bda8-8234c84c49b3
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

