HTTP/1.1 302 
X-Request-Id: a81f62c7-c77d-4f62-b63c-ec662f16f804
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:05 GMT

