HTTP/1.1 302 
X-Request-Id: 859819c1-b0be-476c-bdb2-207af8a77a48
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

