HTTP/1.1 302 
X-Request-Id: a1edaf64-6cb3-4415-9584-8d77e2a7831a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:57 GMT

