HTTP/1.1 302 
X-Request-Id: 344122dd-8518-4687-9b20-2c0b3030c0af
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

