HTTP/1.1 403 
X-Request-Id: a2f5b027-720e-4981-bffc-69260fafc5b8
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:13 GMT

{"instance":"urn:uuid:a2f5b027-720e-4981-bffc-69260fafc5b8","status":403,"title":"Forbidden"}