HTTP/1.1 302 
X-Request-Id: 0df126f5-38ac-4062-b35e-f8688fa7c9ff
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:09 GMT

