HTTP/1.1 302 
X-Request-Id: d6310ee9-2b07-4115-9356-74326d25cecb
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

