HTTP/1.1 201 
X-Request-Id: ca794f3f-e13e-48b1-bf15-c5f21c0829fa
Location: /api/links/wsuTTVM3
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:09 GMT

{"code":"wsuTTVM3","shortUrl":"http://localhost:8080/wsuTTVM3","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T13:36:00Z"}