HTTP/1.1 302 
X-Request-Id: 75459bdd-e0c2-4f49-9a98-a59fa61d6956
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:52 GMT

