HTTP/1.1 302 
X-Request-Id: 4b714e63-259c-44af-b992-4daf925c2aa4
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

