HTTP/1.1 302 
X-Request-Id: bd0f0a17-1faa-4419-9af7-5cad03a04d0d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:43 GMT

