HTTP/1.1 302 
X-Request-Id: 25e60d4a-bda0-4164-990f-df366f343bd8
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

