HTTP/1.1 302 
X-Request-Id: 696db780-3005-4196-9178-0e8fe685135a
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:51 GMT

