HTTP/1.1 302 
X-Request-Id: 100fa8b8-a07d-48a3-9866-9295fa4cb79d
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

