HTTP/1.1 302 
X-Request-Id: 4865ef86-4952-4100-aa6e-fc3c3e42cf93
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:42 GMT

