HTTP/1.1 302 
X-Request-Id: 45e2b942-d8ec-426e-8f04-05be7b104878
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:55 GMT

