HTTP/1.1 302 
X-Request-Id: 29c91890-043b-4793-b9ba-be200066a481
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:53 GMT

