HTTP/1.1 302 
X-Request-Id: bb5ba76c-6f22-4ad2-a4d6-81400a4dfea9
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:54 GMT

