HTTP/1.1 302 
X-Request-Id: 83a4dd47-a76c-43d4-a1ce-616c108f3d9e
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:11:44 GMT

