HTTP/1.1 201 
X-Request-Id: 77d7ca3b-6396-43e5-b238-5e210f7a5b89
Location: /api/links/ks0OHwXl
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:12:05 GMT

{"code":"ks0OHwXl","shortUrl":"http://localhost:8080/ks0OHwXl","url":"https://example.com/QA06-AUDIT-TARGET-CANARY","state":"active","createdAt":"2026-10-01T12:32:00Z"}