HTTP/1.1 302 
X-Request-Id: ae84c47f-8d74-4f74-be7f-9d9c96482660
Location: https://example.com/QA06-AUDIT-TARGET-CANARY
Cache-Control: no-store
Content-Length: 0
Date: Sun, 04 Oct 2026 02:12:18 GMT

