HTTP/1.1 200 
X-Request-Id: 4eea4f47-9026-4dd0-b762-0793f65c9c29
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:28:41 GMT

{"items":[{"occurredAt":"2026-10-04T02:28:41.626Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"nsEMn19Z","requestId":"99905e13-07ea-4552-9227-8f9fa8ae8cf6","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}