HTTP/1.1 200 
X-Request-Id: 1df441e7-295d-43ad-8e9b-af5b02b19b53
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:28:44 GMT

{"items":[{"occurredAt":"2026-10-04T02:28:44.077Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"5dasongR","requestId":"311a08e4-56d9-4884-a79c-7753f3c93033","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}