HTTP/1.1 200 
X-Request-Id: 2e6d1fe8-7423-4c5f-aa6c-66c28ffdf4e9
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:28:46 GMT

{"items":[{"occurredAt":"2026-10-04T02:28:46.722Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"UstHibCl","requestId":"8422009c-8fa6-4713-ae02-89dff96d497d","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}