HTTP/1.1 201 
X-Request-Id: 812f6249-8f15-4a1f-8ea5-b298a5439d32
Location: /api/links/ccPGUntH
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:28:49 GMT

{"code":"ccPGUntH","shortUrl":"http://localhost:8080/ccPGUntH","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T02:28:49.304Z"}