HTTP/1.1 201 
X-Request-Id: 89976a1f-af37-4ae3-a011-94d84855be5e
Location: /api/links/sG1bwAuY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:28:59 GMT

{"code":"sG1bwAuY","shortUrl":"http://localhost:8080/sG1bwAuY","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T02:28:59.904Z"}