HTTP/1.1 200 
X-Request-Id: ded242b2-20dc-4897-ae36-4b1afc0edde0
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:28:59 GMT

{"items":[{"occurredAt":"2026-10-04T02:28:59.933Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"sG1bwAuY","requestId":"89976a1f-af37-4ae3-a011-94d84855be5e","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}