HTTP/1.1 200 
X-Request-Id: b9674111-d6b7-4dcc-9f0c-cd20619c57f0
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:29:04 GMT

{"items":[{"occurredAt":"2026-10-04T02:29:04.939Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"79b6kGMm","requestId":"b861e483-2413-4417-9801-f246cda71c6a","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}