HTTP/1.1 201 
X-Request-Id: 84e9bdf4-e4b8-49ea-a5a6-8b21aacdcb62
Location: /api/links/6KVS8Det
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:29:07 GMT

{"code":"6KVS8Det","shortUrl":"http://localhost:8080/6KVS8Det","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T02:29:07.623Z"}