HTTP/1.1 200 
X-Request-Id: 1cedf3d4-725f-4042-96e5-7779e31b9a5d
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 02:29:10 GMT

{"items":[{"occurredAt":"2026-10-04T02:29:10.253Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"ELQjd9Ky","requestId":"75968087-1890-448b-b85e-9c8e33b608c8","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}