HTTP/1.1 201 
X-Request-Id: 5cbb9b52-77c3-40ba-ba07-6a23c5405088
Location: /api/links/kmHkaZFm
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:03:49 GMT

{"code":"kmHkaZFm","shortUrl":"http://localhost:8080/kmHkaZFm","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:03:49.153Z"}