HTTP/1.1 200 
X-Request-Id: 96a4b36d-150f-42ba-b280-6550e5300309
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:03:49 GMT

{"items":[{"occurredAt":"2026-10-04T01:03:49.185Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"kmHkaZFm","requestId":"5cbb9b52-77c3-40ba-ba07-6a23c5405088","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}