HTTP/1.1 403 
X-Request-Id: 6f2ae50d-91d8-4a9c-835d-c127bfd9e9f7
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:17 GMT

{"instance":"urn:uuid:6f2ae50d-91d8-4a9c-835d-c127bfd9e9f7","status":403,"title":"Forbidden"}