HTTP/1.1 200 
X-Request-Id: e0587bf9-4add-4860-8f0c-aae3f10a2a8b
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:21 GMT

{"items":[{"occurredAt":"2026-10-04T01:05:21.702Z","actor":"anonymous","action":"link.create","entity":"link","entityId":"eGLBmqV8","requestId":"09982141-8b1f-4cfc-9491-a95bb759d023","before":null,"after":{"url":"https://example.com/qa06/client-group","state":"active"}}],"next":null}