HTTP/1.1 403 
X-Request-Id: 7ac4d87f-5f5b-4afd-9eb5-6fdcd5dd9a06
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:21 GMT

{"instance":"urn:uuid:7ac4d87f-5f5b-4afd-9eb5-6fdcd5dd9a06","status":403,"title":"Forbidden"}