HTTP/1.1 200 
X-Request-Id: c65fd0a7-38d8-4c56-9808-e162220297ce
Content-Type: application/json
Content-Length: 181
Date: Sun, 04 Oct 2026 01:05:21 GMT

{"code":"eGLBmqV8","totalClicks":3,"clicksPerDay":[{"date":"2026-10-04","clicks":3,"uniqueVisitors":2,"botClicks":0}],"topReferrers":[{"referrer":"https://ref.example","clicks":3}]}