HTTP/1.1 429 
X-Request-Id: 1005a3f4-3994-4ce5-9f91-da300aa83fd2
Retry-After: 30
Content-Type: application/problem+json
Content-Length: 101
Date: Sun, 04 Oct 2026 01:05:27 GMT

{"instance":"urn:uuid:1005a3f4-3994-4ce5-9f91-da300aa83fd2","status":429,"title":"Too Many Requests"}