HTTP/1.1 201 
X-Request-Id: 10b0e7e5-750a-499b-9003-3e0fb7496b8e
Location: /api/links/3hLDWXrV
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:29 GMT

{"code":"3hLDWXrV","shortUrl":"http://localhost:8080/3hLDWXrV","url":"https://example.com/qa06/client-group","state":"active","createdAt":"2026-10-04T01:05:29.516Z"}