HTTP/1.1 403 
X-Request-Id: f2c5cb56-4e2c-4e1a-9e4a-e16a934a694a
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:34 GMT

{"instance":"urn:uuid:f2c5cb56-4e2c-4e1a-9e4a-e16a934a694a","status":403,"title":"Forbidden"}