HTTP/1.1 403 
X-Request-Id: 7105413e-03a5-4afd-8afb-b555c7a9c11a
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:39 GMT

{"instance":"urn:uuid:7105413e-03a5-4afd-8afb-b555c7a9c11a","status":403,"title":"Forbidden"}