HTTP/1.1 403 
X-Request-Id: 4e2e1fe7-02f6-43cf-8e7c-dab7ed1e6b1d
Content-Type: application/problem+json
Transfer-Encoding: chunked
Date: Sun, 04 Oct 2026 01:05:39 GMT

{"instance":"urn:uuid:4e2e1fe7-02f6-43cf-8e7c-dab7ed1e6b1d","status":403,"title":"Forbidden"}